//
// Generated by Microsoft (R) HLSL Shader Compiler 9.30.9200.16384
//
//   using 3Dmigoto v1.2.45 on Thu Jul 15 15:23:56 2021
//
//
// Buffer Definitions: 
//
// cbuffer PerSceneConsts
// {
//
//   row_major float4x4 projectionMatrix;// Offset:    0 Size:    64 [unused]
//   row_major float4x4 viewMatrix;     // Offset:   64 Size:    64 [unused]
//   row_major float4x4 viewProjectionMatrix;// Offset:  128 Size:    64 [unused]
//   row_major float4x4 inverseProjectionMatrix;// Offset:  192 Size:    64
//   row_major float4x4 inverseViewMatrix;// Offset:  256 Size:    64
//   row_major float4x4 inverseViewProjectionMatrix;// Offset:  320 Size:    64 [unused]
//   float4 eyeOffset;                  // Offset:  384 Size:    16
//   float4 adsZScale;                  // Offset:  400 Size:    16 [unused]
//   float4 hdrControl0;                // Offset:  416 Size:    16 [unused]
//   float4 hdrControl1;                // Offset:  432 Size:    16 [unused]
//   float4 fogColor;                   // Offset:  448 Size:    16 [unused]
//   float4 fogConsts;                  // Offset:  464 Size:    16 [unused]
//   float4 fogConsts2;                 // Offset:  480 Size:    16 [unused]
//   float4 fogConsts3;                 // Offset:  496 Size:    16 [unused]
//   float4 fogConsts4;                 // Offset:  512 Size:    16 [unused]
//   float4 fogConsts5;                 // Offset:  528 Size:    16 [unused]
//   float4 fogConsts6;                 // Offset:  544 Size:    16 [unused]
//   float4 fogConsts7;                 // Offset:  560 Size:    16 [unused]
//   float4 fogConsts8;                 // Offset:  576 Size:    16 [unused]
//   float4 fogConsts9;                 // Offset:  592 Size:    16 [unused]
//   float3 sunFogDir;                  // Offset:  608 Size:    12 [unused]
//   float4 sunFogColor;                // Offset:  624 Size:    16 [unused]
//   float2 sunFog;                     // Offset:  640 Size:     8 [unused]
//   float4 zNear;                      // Offset:  656 Size:    16 [unused]
//   float3 clothPrimaryTint;           // Offset:  672 Size:    12 [unused]
//   float3 clothSecondaryTint;         // Offset:  688 Size:    12 [unused]
//   float4 renderTargetSize;           // Offset:  704 Size:    16
//   float4 upscaledTargetSize;         // Offset:  720 Size:    16 [unused]
//   float4 materialColor;              // Offset:  736 Size:    16 [unused]
//   float4 cameraUp;                   // Offset:  752 Size:    16 [unused]
//   float4 cameraLook;                 // Offset:  768 Size:    16 [unused]
//   float4 cameraSide;                 // Offset:  784 Size:    16 [unused]
//   float4 cameraVelocity;             // Offset:  800 Size:    16 [unused]
//   float4 skyMxR;                     // Offset:  816 Size:    16 [unused]
//   float4 skyMxG;                     // Offset:  832 Size:    16 [unused]
//   float4 skyMxB;                     // Offset:  848 Size:    16 [unused]
//   float4 sunMxR;                     // Offset:  864 Size:    16 [unused]
//   float4 sunMxG;                     // Offset:  880 Size:    16 [unused]
//   float4 sunMxB;                     // Offset:  896 Size:    16 [unused]
//   float4 skyRotationTransition;      // Offset:  912 Size:    16 [unused]
//   float4 debugColorOverride;         // Offset:  928 Size:    16 [unused]
//   float4 debugAlphaOverride;         // Offset:  944 Size:    16 [unused]
//   float4 debugNormalOverride;        // Offset:  960 Size:    16 [unused]
//   float4 debugSpecularOverride;      // Offset:  976 Size:    16 [unused]
//   float4 debugGlossOverride;         // Offset:  992 Size:    16 [unused]
//   float4 debugOcclusionOverride;     // Offset: 1008 Size:    16 [unused]
//   float4 debugStreamerControl;       // Offset: 1024 Size:    16 [unused]
//   float4 emblemLUTSelector;          // Offset: 1040 Size:    16 [unused]
//   float4 colorMatrixR;               // Offset: 1056 Size:    16 [unused]
//   float4 colorMatrixG;               // Offset: 1072 Size:    16 [unused]
//   float4 colorMatrixB;               // Offset: 1088 Size:    16 [unused]
//   float4 gameTime;                   // Offset: 1104 Size:    16 [unused]
//   float4 gameTick;                   // Offset: 1120 Size:    16
//   float4 subpixelOffset;             // Offset: 1136 Size:    16
//   float4 viewportDimensions;         // Offset: 1152 Size:    16 [unused]
//   float4 viewSpaceScaleBias;         // Offset: 1168 Size:    16 [unused]
//   float4 ui3dUVSetup0;               // Offset: 1184 Size:    16 [unused]
//   float4 ui3dUVSetup1;               // Offset: 1200 Size:    16 [unused]
//   float4 ui3dUVSetup2;               // Offset: 1216 Size:    16 [unused]
//   float4 ui3dUVSetup3;               // Offset: 1232 Size:    16 [unused]
//   float4 ui3dUVSetup4;               // Offset: 1248 Size:    16 [unused]
//   float4 ui3dUVSetup5;               // Offset: 1264 Size:    16 [unused]
//   float4 clipSpaceLookupScale;       // Offset: 1280 Size:    16 [unused]
//   float4 clipSpaceLookupOffset;      // Offset: 1296 Size:    16 [unused]
//   uint4 computeSpriteControl;        // Offset: 1312 Size:    16 [unused]
//   float4 invBcTexSizes;              // Offset: 1328 Size:    16 [unused]
//   float4 invMaskTexSizes;            // Offset: 1344 Size:    16 [unused]
//   float4 relHDRExposure;             // Offset: 1360 Size:    16
//   uint4 triDensityFlags;             // Offset: 1376 Size:    16 [unused]
//   float4 triDensityParams;           // Offset: 1392 Size:    16 [unused]
//   float4 voldecalRevealTextureInfo;  // Offset: 1408 Size:    16 [unused]
//   float4 extraClipPlane0;            // Offset: 1424 Size:    16 [unused]
//   float4 extraClipPlane1;            // Offset: 1440 Size:    16 [unused]
//   float4 shaderDebug;                // Offset: 1456 Size:    16 [unused]
//   uint isDepthHack;                  // Offset: 1472 Size:     4 [unused]
//
// }
//
// cbuffer LightingGlobals
// {
//
//   uint numLights;                    // Offset:    0 Size:     4
//   uint numRefProbes;                 // Offset:    4 Size:     4
//   uint numRefProbeBlends;            // Offset:    8 Size:     4 [unused]
//   uint numDedicatedLights;           // Offset:   12 Size:     4 [unused]
//   float4 clearColor;                 // Offset:   16 Size:    16 [unused]
//   float4 sssParams;                  // Offset:   32 Size:    16 [unused]
//   
//   struct CoreFogConstants
//   {
//       
//       float4 fogColor;               // Offset:   48
//       float4 sunFogColor;            // Offset:   64
//       float K0;                      // Offset:   80
//       float skyK0;                   // Offset:   84
//       float expMul;                  // Offset:   88
//       float expAdd;                  // Offset:   92
//       float heightFalloff;           // Offset:   96
//       float skyHeightFalloff;        // Offset:  100
//       float K0b;                     // Offset:  104
//       float padding0;                // Offset:  108
//       float skyK0b;                  // Offset:  112
//       float3 wldSunFogDir;           // Offset:  116
//       float2 sunFogAngles;           // Offset:  128
//       float atmospheresunstrength;   // Offset:  136
//       float atmosphereMieSchlickK;   // Offset:  140
//       float2 atmosphereskyfogdensityatcamera;// Offset:  144
//       float atmosphereExtinctionIntensity;// Offset:  152
//       float atmosphereInScatterIntensity;// Offset:  156
//       float3 atmosphereRayleighDensity;// Offset:  160
//       float atmospherehazebasedist;  // Offset:  172
//       float3 atmosphereMieDensity;   // Offset:  176
//       float atmospherehazefadedist;  // Offset:  188
//       float3 atmosphereTotalDensity; // Offset:  192
//       float worldfogskysize;         // Offset:  204
//       float3 atmosphereInScatterIntensityOverTotalDensity;// Offset:  208
//       float blendAmount;             // Offset:  220
//       float2 atmosphereskyfogheightdensityscale;// Offset:  224
//       float2 atmospherefogdistanceoffset;// Offset:  232
//       float2 atmospherefogdistancedensityscale;// Offset:  240
//       float2 atmospherefogheightdensityscale;// Offset:  248
//       float2 atmospherefogdensityatcamera;// Offset:  256
//       float2 padding1;               // Offset:  264
//
//   } fogConstants;                    // Offset:   48 Size:   224
//   
//   struct CoreSunConstants
//   {
//       
//       float3 wldDir;                 // Offset:  272
//       float splitDepthOffset;        // Offset:  284
//       float3 color;                  // Offset:  288
//       float specScale;               // Offset:  300
//       float globalProbeExposure;     // Offset:  304
//       float3 avgGlobalProbeColor;    // Offset:  308
//       float4 splitPinTransform[3];   // Offset:  320
//       uint sunCookieIndex;           // Offset:  368
//       float sunCookieIntensity;      // Offset:  372
//       float sunVolumetricCookieIntensity;// Offset:  376
//       uint toolsGfxDisableSunShadow; // Offset:  380
//       float4 sunCookieTransform[2];  // Offset:  384
//       float intensity;               // Offset:  416
//       int splitArrayOffset;          // Offset:  420
//       float2 pad0;                   // Offset:  424
//       
//       struct SSTLightingConstants
//       {
//           
//           struct SSTConstants
//           {
//               
//               float2 dimensionInTiles;// Offset:  432
//               float inchesPerTexel;  // Offset:  440
//               float spanInInches;    // Offset:  444
//
//           } constants;               // Offset:  432
//           row_major float4x4 offToPinTransform;// Offset:  448
//           float coordScale;          // Offset:  512
//           uint rootOffset;           // Offset:  516
//           uint2 pad0;                // Offset:  520
//
//       } sstLightingConstants;        // Offset:  432
//
//   } sunConstants;                    // Offset:  272 Size:   256
//   
//   struct SSTMinMaxConstants
//   {
//       
//       float2 sstToMinMaxScale;       // Offset:  528
//       float2 pad0;                   // Offset:  536
//       float2 halfMinTexelSize;       // Offset:  544
//       float rcpInchesDimLevel0;      // Offset:  552
//       float shadowBiasInches;        // Offset:  556
//
//   } minMaxConstants;                 // Offset:  528 Size:    32 [unused]
//   
//   struct CoreGlobalProbePack
//   {
//       
//       uint4 data[3];                 // Offset:  560
//
//   } globalProbeConstants;            // Offset:  560 Size:    48
//   
//   struct CoreWeatherConsts
//   {
//       
//       float rain;                    // Offset:  608
//       float windSpeed;               // Offset:  612
//       float windDirSin;              // Offset:  616
//       float windDirCos;              // Offset:  620
//       float weatherTile;             // Offset:  624
//       float3 weatherVector;          // Offset:  628
//       float3 weatherVector2;         // Offset:  640
//       float padding0;                // Offset:  652
//       float3 weatherTint;            // Offset:  656
//       float padding1;                // Offset:  668
//       float3 weatherTint2;           // Offset:  672
//       float padding2;                // Offset:  684
//
//   } weather;                         // Offset:  608 Size:    80 [unused]
//   
//   struct SSTLightingConstants
//   {
//       
//       struct SSTConstants
//       {
//           
//           float2 dimensionInTiles;   // Offset:  688
//           float inchesPerTexel;      // Offset:  696
//           float spanInInches;        // Offset:  700
//
//       } constants;                   // Offset:  688
//       row_major float4x4 offToPinTransform;// Offset:  704
//       float coordScale;              // Offset:  768
//       uint rootOffset;               // Offset:  772
//       uint2 pad0;                    // Offset:  776
//
//   } outdoorSSTConstants;             // Offset:  688 Size:    96 [unused]
//   float4 pinToWorldZ;                // Offset:  784 Size:    16 [unused]
//   
//   struct CoreVolumetricConstants
//   {
//       
//       uint firstSpotLight;           // Offset:  800
//       uint lastSpotLight;            // Offset:  804
//       uint firstOmniLight;           // Offset:  808
//       uint lastOmniLight;            // Offset:  812
//       uint firstProbe;               // Offset:  816
//       uint lastProbe;                // Offset:  820
//       uint padding0;                 // Offset:  824
//       uint padding1;                 // Offset:  828
//
//   } volumetric;                      // Offset:  800 Size:    32 [unused]
//   uint viewID;                       // Offset:  832 Size:     4
//   uint enableCountDebug;             // Offset:  836 Size:     4
//   uint centerGroupIDx;               // Offset:  840 Size:     4
//   uint centerGroupIDy;               // Offset:  844 Size:     4
//   uint viewmodelSunShadowRaw;        // Offset:  848 Size:     4 [unused]
//   uint debugDrawOverlayType;         // Offset:  852 Size:     4
//   float drawNumLighstScale;          // Offset:  856 Size:     4
//   float drawNumLightsAlpha;          // Offset:  860 Size:     4
//   uint probeDebug;                   // Offset:  864 Size:     4 [unused]
//   float probeDebugRadius;            // Offset:  868 Size:     4 [unused]
//   uint showSunVis;                   // Offset:  872 Size:     4 [unused]
//   uint enableAO;                     // Offset:  876 Size:     4
//   uint showAO;                       // Offset:  880 Size:     4
//   uint numGpuCullTilesWidth;         // Offset:  884 Size:     4 [unused]
//   uint numGpuCullTilesHeight;        // Offset:  888 Size:     4 [unused]
//   int permuteHighlight;              // Offset:  892 Size:     4
//   uint overdrawOverlayMaxValue;      // Offset:  896 Size:     4 [unused]
//   float overdrawOverlayAlpha;        // Offset:  900 Size:     4 [unused]
//   uint overdrawDecals;               // Offset:  904 Size:     4 [unused]
//   uint overdrawDecalsLayers;         // Offset:  908 Size:     4 [unused]
//   uint permuteStride;                // Offset:  912 Size:     4
//   uint numDecals;                    // Offset:  916 Size:     4 [unused]
//   uint numStaticDecals;              // Offset:  920 Size:     4 [unused]
//   uint numDynamicDecals;             // Offset:  924 Size:     4 [unused]
//   uint numOverrideProbes;            // Offset:  928 Size:     4
//   uint enableDitheredShadow;         // Offset:  932 Size:     4
//   uint oitMaxEntries;                // Offset:  936 Size:     4 [unused]
//   uint numAttenuationVolumes;        // Offset:  940 Size:     4 [unused]
//
// }
//
// cbuffer LightingPackCBuffer
// {
//
//   struct CoreLightConstantsPack
//   {
//       
//       uint4 data[15];                // Offset:    0
//
//   } lightConstantsCB[273];           // Offset:    0 Size: 65520
//
// }
//
// cbuffer RefProbePackCBuffer
// {
//
//   struct CoreReflectionProbePack
//   {
//       
//       uint4 data[14];                // Offset:    0
//
//   } refProbeConstantsCB[273];        // Offset:    0 Size: 61152
//
// }
//
// cbuffer RefProbeBlendPackCBuffer
// {
//
//   struct CoreReflectionProbeAttenuationPack
//   {
//       
//       uint4 data[6];                 // Offset:    0
//
//   } refProbeAttenuationConstantsCB[682];// Offset:    0 Size: 65472
//
// }
//
// Resource bind info for gPermutedTilingBuffer
// {
//
//   struct PermutedTilingBuffer
//   {
//       
//       uint2 data;                    // Offset:    0
//
//   } $Element;                        // Offset:    0 Size:     8
//
// }
//
// Resource bind info for lightingDebug
// {
//
//   struct LightingDebug
//   {
//       
//       struct LightingDebugCounts
//       {
//           
//           uint visibleLights;        // Offset:    0
//           uint activeLights;         // Offset:    4
//           uint litLights;            // Offset:    8
//           uint visibleProbes;        // Offset:   12
//           uint activeProbes;         // Offset:   16
//
//       } maxCounts;                   // Offset:    0
//       
//       struct LightingDebugCounts
//       {
//           
//           uint visibleLights;        // Offset:   20
//           uint activeLights;         // Offset:   24
//           uint litLights;            // Offset:   28
//           uint visibleProbes;        // Offset:   32
//           uint activeProbes;         // Offset:   36
//
//       } centerCounts;                // Offset:   20
//       
//       struct LightingDebugCounts
//       {
//           
//           uint visibleLights;        // Offset:   40
//           uint activeLights;         // Offset:   44
//           uint litLights;            // Offset:   48
//           uint visibleProbes;        // Offset:   52
//           uint activeProbes;         // Offset:   56
//
//       } sumDeferredCounts;           // Offset:   40
//       
//       struct LightingDebugCounts
//       {
//           
//           uint visibleLights;        // Offset:   60
//           uint activeLights;         // Offset:   64
//           uint litLights;            // Offset:   68
//           uint visibleProbes;        // Offset:   72
//           uint activeProbes;         // Offset:   76
//
//       } sumForwardCounts;            // Offset:   60
//       float3 cameraWorldPos;         // Offset:   80
//       float3 pickedWldPos;           // Offset:   92
//       uint numPickedLights;          // Offset:  104
//       uint numPickedProbes;          // Offset:  108
//       
//       struct LightingDebugLight
//       {
//           
//           uint flags;                // Offset:  112
//           float3 wldOrigin;          // Offset:  116
//           float activeAttenuation;   // Offset:  128
//           float litAttenuation;      // Offset:  132
//
//       } pickedLights[32];            // Offset:  112
//       
//       struct LightingDebugProbe
//       {
//           
//           uint flags;                // Offset:  880
//           float3 wldOrigin;          // Offset:  884
//           float weight;              // Offset:  896
//
//       } pickedProbes[32];            // Offset:  880
//       uint overdrawHistogram[64];    // Offset: 1520
//       uint overdrawSum;              // Offset: 1776
//       uint overdrawMax;              // Offset: 1780
//       float padding0;                // Offset: 1784
//       float padding1;                // Offset: 1788
//
//   } $Element;                        // Offset:    0 Size:  1792
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// samplerLinear                     sampler      NA          NA             s2      1 
// samplerLinearClamp                sampler      NA          NA             s4      1 
// ShadowSamplerComparisonState    sampler_c      NA          NA            s13      1 
// GBufferDiffuseColor               texture  float4          2d             t0      1 
// GBufferNormalAndGloss             texture  float4          2d             t1      1 
// GBufferSpecularColorAndOcclusion    texture  float4          2d             t2      1 
// GBufferDepth                      texture   float          2d             t4      1 
// gEnvBRDFGeneric                   texture  float2          2d             t5      1 
// gReflectionProbeArray             texture  float3   cubearray             t8      1 
// gSpotShadowmapArray               texture   float     2darray             t9      1 
// gOmniShadowmapArray               texture   float   cubearray            t10      1 
// gProbeXArray                      texture  float3          3d            t17      1 
// gProbeYArray                      texture  float3          3d            t18      1 
// gProbeZArray                      texture  float3          3d            t19      1 
// gCookieArray                      texture  float4     2darray            t20      1 
// gPermutedTilingBuffer             texture  struct         r/o            t25      1 
// gSSAOTexture                      texture   float          2d            t27      1 
// gSSAODepthTexture                 texture   float          2d            t28      1 
// litBuffer                             UAV  float3          2d             u0      1 
// lightingDebug                         UAV  struct         r/w             u2      1 
// PerSceneConsts                    cbuffer      NA          NA            cb1      1 
// LightingGlobals                   cbuffer      NA          NA            cb2      1 
// LightingPackCBuffer               cbuffer      NA          NA            cb9      1 
// RefProbePackCBuffer               cbuffer      NA          NA           cb10      1 
// RefProbeBlendPackCBuffer          cbuffer      NA          NA           cb11      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_immediateConstantBuffer { { -0.80811429, 0.80811429, 0, 0},
                              { 0, -1.000000, 0, 0},
                              { 0.60605717, 0.60605717, 0, 0},
                              { -0.71428573, 0, 0, 0},
                              { 0.40411428, -0.40411428, 0, 0},
                              { 0, 0.42857143, 0, 0},
                              { -0.20205714, -0.20205714, 0, 0},
                              { 0.14285715, 0, 0, 0} }
dcl_constantbuffer CB1[86], immediateIndexed
dcl_constantbuffer CB2[59], immediateIndexed
dcl_constantbuffer CB9[4095], dynamicIndexed
dcl_constantbuffer CB10[3822], dynamicIndexed
dcl_constantbuffer CB11[4092], dynamicIndexed
dcl_sampler s2, mode_default
dcl_sampler s4, mode_default
dcl_sampler s13, mode_comparison
dcl_resource_texture2d (float,float,float,float) t0
dcl_resource_texture2d (float,float,float,float) t1
dcl_resource_texture2d (float,float,float,float) t2
dcl_resource_texture2d (float,float,float,float) t4
dcl_resource_texture2d (float,float,float,float) t5
dcl_resource_texturecubearray (float,float,float,float) t8
dcl_resource_texture2darray (float,float,float,float) t9
dcl_resource_texturecubearray (float,float,float,float) t10
dcl_resource_texture3d (float,float,float,float) t17
dcl_resource_texture3d (float,float,float,float) t18
dcl_resource_texture3d (float,float,float,float) t19
dcl_resource_texture2darray (float,float,float,float) t20
dcl_resource_structured t25, 8
dcl_resource_texture2d (float,float,float,float) t27
dcl_resource_texture2d (float,float,float,float) t28
dcl_uav_typed_texture2d (float,float,float,float) u0
dcl_uav_structured u2, 1792
dcl_input vThreadIDInGroupFlattened
dcl_input vThreadGroupID.x
dcl_input vThreadIDInGroup.xy
dcl_temps 38
dcl_tgsm_raw g0, 4
dcl_tgsm_raw g1, 20
dcl_tgsm_raw g2, 20
dcl_thread_group 8, 8, 1
if_z vThreadIDInGroupFlattened.x
  store_raw g0.x, l(0), l(0)
  store_raw g1.xyzw, l(0), l(0,0,0,0)
  store_raw g1.x, l(16), l(0)
  store_raw g2.xyzw, l(0), l(0,0,0,0)
  store_raw g2.x, l(16), l(0)
endif 
sync_g_t
imad r0.x, cb2[57].x, l(63), vThreadGroupID.x
ld_structured_indexable(structured_buffer, stride=8)(mixed,mixed,mixed,mixed) r0.xy, r0.x, l(0), t25.xyxx
and r0.zw, r0.xxxy, l(0, 0, 4095, 4095)
imad r1.xy, r0.zwzz, l(8, 8, 0, 0), vThreadIDInGroup.xyxx
mov r1.zw, l(0,0,0,0)
ld_indexable(texture2d)(float,float,float,float) r2.xyzw, r1.xyww, t1.xyzw
ftou r3.xy, cb1[44].xyxx
ult r3.xy, r1.xyxx, r3.xyxx
and r3.x, r3.y, r3.x
lt r3.y, l(0.000000), r2.z
and r3.x, r3.y, r3.x
if_z r3.x
  ret 
endif 
ld_indexable(texture2d)(float,float,float,float) r3.y, r1.xyww, t4.yxzw
ld_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.xyww, t2.xyzw
utof r3.zw, r1.xxxy
add r5.xy, r3.zwzz, l(0.500000, 0.500000, 0.000000, 0.000000)
ge r6.x, r3.y, l(0.984375)
mul r5.z, r3.y, l(1.01587307)
mad r3.y, r3.y, l(64.000000), l(-63.000000)
movc r3.y, r6.x, r3.y, r5.z
max r3.y, r3.y, l(0.00000001)
rcp r6.y, r3.y
and r3.xy, r3.xxxx, r6.xyxx
mul r5.zw, r5.xxxy, cb1[44].zzzw
gather4_indexable(texture2d)(float,float,float,float) r6.xyzw, r5.zwzz, t27.xyzw, s4.x
gather4_indexable(texture2d)(float,float,float,float) r7.xyzw, r5.zwzz, t28.xyzw, s4.x
mul r5.zw, r5.xxxy, l(0.000000, 0.000000, 0.500000, 0.500000)
frc r5.zw, r5.zzzw
add r8.xy, -r5.wzww, l(1.000000, 1.000000, 0.000000, 0.000000)
mul r9.y, r8.x, r8.y
mul r9.xz, r5.zzwz, r8.xxyx
mul r9.w, r5.w, r5.z
dp4 r5.z, r6.xyzw, r9.xyzw
add r7.xyzw, -r3.yyyy, r7.xyzw
min r5.w, |r7.w|, |r7.z|
min r5.w, r5.w, |r7.y|
min r5.w, r5.w, |r7.x|
max r8.x, |r7.w|, |r7.z|
max r8.x, |r7.y|, r8.x
max r7.x, |r7.x|, r8.x
eq r7.yzw, r5.wwww, |r7.yyzw|
movc r5.w, r7.y, r6.y, r6.x
movc r5.w, r7.z, r6.z, r5.w
movc r5.w, r7.w, r6.w, r5.w
mul r6.x, r3.y, l(0.010000)
lt r6.x, r6.x, r7.x
movc r5.z, r6.x, r5.w, r5.z
mul r4.z, r4.z, r5.z
if_nz cb2[55].x
  mul r5.z, r4.z, l(0.750000)
  store_uav_typed u0.xyzw, r1.xyyy, r5.zzzz
  ret 
else 
  movc r5.z, cb2[54].w, r4.z, l(1.000000)
endif 
ge r4.z, r2.z, l(0.500000)
ld_indexable(texture2d)(float,float,float,float) r6.xyz, r1.xyww, t0.xyzw
ld_aoffimmi_indexable(-1,0,0)(texture2d)(float,float,float,float) r7.xyz, r1.xyww, t2.xywz
ld_aoffimmi_indexable(0,-1,0)(texture2d)(float,float,float,float) r8.xyz, r1.xyww, t2.xywz
ld_aoffimmi_indexable(1,0,0)(texture2d)(float,float,float,float) r9.xyz, r1.xyww, t2.xywz
ld_aoffimmi_indexable(0,1,0)(texture2d)(float,float,float,float) r10.xyz, r1.xyzw, t2.xywz
add r1.zw, r5.xxxy, -cb1[71].xxxy
mul r1.zw, r1.zzzw, cb1[44].zzzw
mad r1.zw, r1.zzzw, l(0.000000, 0.000000, 2.000000, -2.000000), l(0.000000, 0.000000, -1.000000, 1.000000)
mul r11.x, r1.z, cb1[12].x
mul r11.y, r1.w, cb1[13].y
mov r11.zw, l(0,0,1.000000,1.000000)
mul r5.xyw, r3.yyyy, r11.xyxz
mul r11.xyz, r5.yyyy, cb1[17].xyzx
mad r11.xyz, r5.xxxx, cb1[16].xyzx, r11.xyzx
mad r11.xyz, r5.wwww, cb1[18].xyzx, r11.xyzx
mad r1.z, r2.w, l(3.000000), l(0.500000)
ftou r1.z, r1.z
mad r2.xy, r2.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
mul r2.xy, r2.xyxx, l(0.850000, 0.850000, 0.000000, 0.000000)
dp2 r1.w, r2.xyxx, r2.xyxx
add r12.zw, -r1.wwww, l(0.000000, 0.000000, 2.000000, 1.000000)
sqrt r1.w, r12.z
mul r12.xy, r1.wwww, r2.xyxx
and r13.xyzw, r1.zzzz, l(2, 1, 2, 1)
movc r13.xyzw, r13.zwxy, l(-1.000000,-1.000000,1,1), l(1.000000,1.000000,0,0)
xor r1.z, r13.w, r13.z
movc r13.z, r1.z, l(-1.000000), l(1.000000)
mul r2.xyw, r13.xyxz, l(-1.000000, 0.000000, 0.000000, 1.000000)
mul r5.xyw, r13.xyxz, l(1.000000, -2.000000, 0.000000, 1.000000)
mul r12.xyz, r12.xywx, l(0.40824831, 0.70710677, 0.57735026, 0.000000)
mul r2.xyw, r2.xyxw, r12.yyyy
mad r2.xyw, r5.xyxw, r12.xxxx, r2.xyxw
mad r12.xyz, r13.xyzx, r12.zzzz, r2.xywx
movc r1.z, r4.z, l(-0.500000), l(-0.00146628)
add r1.z, r1.z, r2.z
mul_sat r2.y, r1.z, l(2.00982332)
dp3 r1.z, -r11.xyzx, -r11.xyzx
rsq r1.z, r1.z
mul r5.xyw, r1.zzzz, -r11.xyxz
dp2 r1.z, r3.zwzz, l(0.06711056, 0.00583715, 0.000000, 0.000000)
frc r1.z, r1.z
mul r1.z, r1.z, l(52.982918)
frc r1.z, r1.z
mad r1.z, r1.z, l(6.28318548), cb1[70].w
sincos r13.x, r14.x, r1.z
utof r1.zw, r1.yyyx
dp2 r1.z, r1.zwzz, l(0.06711056, 0.00583715, 0.000000, 0.000000)
frc r1.z, r1.z
mul r1.z, r1.z, l(52.982918)
frc r1.z, r1.z
mad r1.z, r1.z, l(6.28318548), cb1[70].w
sincos r15.x, r16.x, r1.z
dp3_sat r2.x, r12.xyzx, r5.xywx
dp3 r1.z, -r5.xywx, r12.xyzx
add r1.z, r1.z, r1.z
mad r17.xyz, r12.xyzx, -r1.zzzz, -r5.xywx
mul r1.z, r2.y, l(17.000000)
exp r1.z, r1.z
add r1.z, r1.z, l(2.000000)
div r1.z, l(2.000000), r1.z
sqrt r1.w, r1.z
mul r2.zw, cb1[44].xxxy, l(0.000000, 0.000000, 0.500000, 0.500000)
ftou r2.zw, r2.zzzw
ieq r2.zw, r1.xxxy, r2.zzzw
and r2.z, r2.w, r2.z
add r2.w, -r2.y, l(1.000000)
mul r3.y, r2.w, l(5.000000)
mad r3.z, r2.w, l(5.000000), l(-2.500000)
mul r3.z, r3.z, l(0.400000)
max r3.z, r3.z, l(0.000000)
mad r13.zw, -r2.wwww, l(0.000000, 0.000000, 10.000000, 5.000000), l(0.000000, 0.000000, 6.857410, 7.085000)
exp r3.w, r13.z
mul r3.w, r2.x, r3.w
mul r3.zw, r3.zzzw, l(0.000000, 0.000000, 100.000000, 9.136810)
mul r4.z, r2.w, r3.y
mad r4.z, -r4.z, l(2.015905), r13.w
exp r4.z, r4.z
mul r4.z, r2.x, r4.z
mul r4.z, r4.z, l(9.708090)
max r3.w, r3.w, r4.z
max r3.w, r3.w, l(1.268160)
iadd r4.z, cb2[0].y, -cb2[58].x
ushr r13.zw, r0.yyyx, l(0, 0, 24, 24)
ubfe r0.xy, l(10, 10, 0, 0), l(12, 12, 0, 0), r0.yxyy
mov r18.x, l(16)
mov r19.yz, l(0,0,1.000000,0)
mov r20.xy, l(0,0,0,0)
mov r21.xz, l(1.000000,0,1.000000,0)
mov r22.xy, l(0,0,0,0)
mov r23.xy, l(0,0,0,0)
mov r24.xyzw, l(0,0,0,0)
mov r25.xyzw, l(0,0,0,0)
mov r6.w, l(0)
loop 
  ieq r7.w, r6.w, l(2)
  breakc_nz r7.w
  movc r7.w, r6.w, r0.x, r13.z
  uge r8.w, r7.w, r4.z
  ult r9.w, r7.w, cb2[0].y
  and r8.w, r8.w, r9.w
  if_nz r8.w
    imul null, r7.w, r7.w, l(14)
    if_nz r2.z
      and r8.w, r25.w, l(3)
      imad r8.w, r8.w, l(20), l(880)
      add r18.yzw, cb1[24].xxyz, cb10[r7.w + 0].xxyz
      store_structured u2.xyzw, cb2[52].x, r8.w, r18.xyzw
    endif 
    iadd r26.w, r25.w, l(1)
    add r15.yzw, r11.xxyz, -cb10[r7.w + 0].xxyz
    and r8.w, l(0x0000ffff), cb10[r7.w + 7].z
    ubfe r9.w, l(6), l(25), cb10[r7.w + 7].z
    imul null, r10.w, r8.w, l(6)
    dp3 r14.w, cb11[r10.w + 0].xyzx, r15.yzwy
    add_sat r14.w, r14.w, cb11[r10.w + 0].w
    dp3 r16.y, cb11[r10.w + 1].xyzx, r15.yzwy
    add_sat r16.y, r16.y, cb11[r10.w + 1].w
    mul r14.w, r14.w, r16.y
    dp3 r16.y, cb11[r10.w + 2].xyzx, r15.yzwy
    add_sat r16.y, r16.y, cb11[r10.w + 2].w
    mul r14.w, r14.w, r16.y
    dp3 r16.y, cb11[r10.w + 3].xyzx, r15.yzwy
    add_sat r16.y, r16.y, cb11[r10.w + 3].w
    mul r14.w, r14.w, r16.y
    dp3 r16.y, cb11[r10.w + 4].xyzx, r15.yzwy
    add_sat r16.y, r16.y, cb11[r10.w + 4].w
    mul r14.w, r14.w, r16.y
    dp3 r16.y, cb11[r10.w + 5].xyzx, r15.yzwy
    add_sat r10.w, r16.y, cb11[r10.w + 5].w
    mul r19.x, r10.w, r14.w
    and r10.w, l(1), cb10[r7.w + 6].x
    movc r16.yz, r10.wwww, r19.xxyx, r19.zzxz
    mov r10.w, cb10[r7.w + 6].x
    mov r27.xy, r16.yzyy
    mov r14.w, l(1)
    loop 
      ige r16.w, r14.w, r9.w
      breakc_nz r16.w
      iadd r16.w, r8.w, r14.w
      imul null, r16.w, r16.w, l(6)
      dp3 r18.y, cb11[r16.w + 0].xyzx, r15.yzwy
      add_sat r18.y, r18.y, cb11[r16.w + 0].w
      mul r18.y, r18.y, r27.x
      dp3 r18.z, cb11[r16.w + 1].xyzx, r15.yzwy
      add_sat r18.z, r18.z, cb11[r16.w + 1].w
      mul r18.y, r18.z, r18.y
      dp3 r18.z, cb11[r16.w + 2].xyzx, r15.yzwy
      add_sat r18.z, r18.z, cb11[r16.w + 2].w
      mul r18.y, r18.z, r18.y
      dp3 r18.z, cb11[r16.w + 3].xyzx, r15.yzwy
      add_sat r18.z, r18.z, cb11[r16.w + 3].w
      mul r18.y, r18.z, r18.y
      dp3 r18.z, cb11[r16.w + 4].xyzx, r15.yzwy
      add_sat r18.z, r18.z, cb11[r16.w + 4].w
      mul r18.y, r18.z, r18.y
      dp3 r18.z, cb11[r16.w + 5].xyzx, r15.yzwy
      add_sat r16.w, r18.z, cb11[r16.w + 5].w
      mul r27.x, r16.w, r18.y
      ushr r18.z, r10.w, l(2)
      ubfe r18.w, l(1), l(2), r10.w
      and r19.x, r18.z, l(2)
      max r19.w, r27.x, r27.y
      mad r16.w, -r18.y, r16.w, l(1.000000)
      mul r16.w, r16.w, r27.y
      movc r21.y, r19.x, r16.w, r19.w
      movc r27.xy, r18.wwww, r27.xyxx, r21.xyxx
      iadd r14.w, r14.w, l(1)
      mov r10.w, r18.z
    endloop 
    mov_sat r27.y, r27.y
    mul r8.w, r27.y, cb10[r7.w + 6].y
    lt r9.w, l(0.000000), r8.w
    if_nz r9.w
      and r9.w, r26.w, l(7)
      iadd r10.w, r9.w, l(-1)
      ult r10.w, r10.w, l(32)
      and r10.w, r2.z, r10.w
      if_nz r10.w
        imad r16.yz, r9.wwww, l(0, 20, 20, 0), l(0, 860, 876, 0)
        ld_structured_indexable(structured_buffer, stride=1792)(mixed,mixed,mixed,mixed) r9.w, cb2[52].x, r16.y, u2.xxxx
        or r9.w, r9.w, l(32)
        store_structured u2.x, cb2[52].x, r16.y, r9.w
        store_structured u2.x, cb2[52].x, r16.z, r8.w
      endif 
      iadd r25.w, r25.w, l(257)
      mad r25.z, r27.y, cb10[r7.w + 6].y, r25.z
      mul r8.w, r8.w, cb10[r7.w + 7].y
      mov r28.x, cb10[r7.w + 7].w
      mov r28.yz, cb10[r7.w + 8].xxyx
      dp3 r9.w, r17.xyzx, r28.xyzx
      dp3 r10.w, r15.yzwy, r28.xyzx
      add r10.w, r10.w, -cb10[r7.w + 8].z
      ge r14.w, r10.w, l(0.000000)
      max r10.w, r3.z, |r10.w|
      movc r10.w, r14.w, r10.w, -r10.w
      max r9.w, -r9.w, l(0.00000010)
      div r9.w, r10.w, r9.w
      min r9.w, |r9.w|, l(131072.000000)
      mov r28.x, cb10[r7.w + 8].w
      mov r28.yz, cb10[r7.w + 9].xxyx
      dp3 r10.w, r17.xyzx, r28.xyzx
      dp3 r14.w, r15.yzwy, r28.xyzx
      add r14.w, r14.w, -cb10[r7.w + 9].z
      ge r16.y, r14.w, l(0.000000)
      max r14.w, r3.z, |r14.w|
      movc r14.w, r16.y, r14.w, -r14.w
      max r10.w, -r10.w, l(0.00000010)
      div r10.w, r14.w, r10.w
      min r9.w, r9.w, |r10.w|
      mov r28.x, cb10[r7.w + 9].w
      mov r28.yz, cb10[r7.w + 10].xxyx
      dp3 r10.w, r17.xyzx, r28.xyzx
      dp3 r14.w, r15.yzwy, r28.xyzx
      add r14.w, r14.w, -cb10[r7.w + 10].z
      ge r16.y, r14.w, l(0.000000)
      max r14.w, r3.z, |r14.w|
      movc r14.w, r16.y, r14.w, -r14.w
      max r10.w, -r10.w, l(0.00000010)
      div r10.w, r14.w, r10.w
      min r9.w, r9.w, |r10.w|
      mov r28.x, cb10[r7.w + 10].w
      mov r28.yz, cb10[r7.w + 11].xxyx
      dp3 r10.w, r17.xyzx, r28.xyzx
      dp3 r14.w, r15.yzwy, r28.xyzx
      add r14.w, r14.w, -cb10[r7.w + 11].z
      ge r16.y, r14.w, l(0.000000)
      max r14.w, r3.z, |r14.w|
      movc r14.w, r16.y, r14.w, -r14.w
      max r10.w, -r10.w, l(0.00000010)
      div r10.w, r14.w, r10.w
      min r9.w, r9.w, |r10.w|
      mov r28.x, cb10[r7.w + 11].w
      mov r28.yz, cb10[r7.w + 12].xxyx
      dp3 r10.w, r17.xyzx, r28.xyzx
      dp3 r14.w, r15.yzwy, r28.xyzx
      add r14.w, r14.w, -cb10[r7.w + 12].z
      ge r16.y, r14.w, l(0.000000)
      max r14.w, r3.z, |r14.w|
      movc r14.w, r16.y, r14.w, -r14.w
      max r10.w, -r10.w, l(0.00000010)
      div r10.w, r14.w, r10.w
      min r9.w, r9.w, |r10.w|
      mov r28.x, cb10[r7.w + 12].w
      mov r28.yz, cb10[r7.w + 13].xxyx
      dp3 r10.w, r17.xyzx, r28.xyzx
      dp3 r14.w, r15.yzwy, r28.xyzx
      add r14.w, r14.w, -cb10[r7.w + 13].z
      ge r16.y, r14.w, l(0.000000)
      max r14.w, r3.z, |r14.w|
      movc r14.w, r16.y, r14.w, -r14.w
      max r10.w, -r10.w, l(0.00000010)
      div r10.w, r14.w, r10.w
      min r9.w, r9.w, |r10.w|
      add r28.x, r15.y, cb10[r7.w + 3].w
      add r28.yz, r15.zzwz, cb10[r7.w + 4].xxyx
      mad r16.yzw, r17.xxyz, r9.wwww, r28.xxyz
      dp3 r10.w, r16.yzwy, r16.yzwy
      sqrt r10.w, r10.w
      div r9.w, r9.w, r10.w
      add r9.w, r9.w, r9.w
      sqrt r9.w, r9.w
      mad r9.w, r2.w, l(5.000000), r9.w
      add r9.w, r9.w, l(-0.844800)
      mov r28.x, cb10[r7.w + 0].w
      mov r28.y, cb10[r7.w + 1].z
      mov r28.z, cb10[r7.w + 2].y
      dp3 r29.x, r16.yzwy, r28.xyzx
      mov r30.xy, cb10[r7.w + 1].xwxx
      mov r30.z, cb10[r7.w + 2].z
      dp3 r29.y, r16.yzwy, r30.xyzx
      mov r31.x, cb10[r7.w + 1].y
      mov r31.yz, cb10[r7.w + 2].xxwx
      dp3 r29.z, r16.yzwy, r31.xyzx
      ubfe r10.w, l(9), l(16), cb10[r7.w + 7].z
      utof r29.w, r10.w
      sample_l_indexable(texturecubearray)(float,float,float,float) r16.yzw, r29.xyzw, t8.wxyz, s2, r9.w
      and r18.yzw, r16.yyzw, l(0, 0x7fffffff, 0x7fffffff, 0x7fffffff)
      ieq r18.yzw, r18.yyzw, l(0, 0x7f800000, 0x7f800000, 0x7f800000)
      or r9.w, r18.z, r18.y
      or r9.w, r18.w, r9.w
      movc r16.yzw, r9.wwww, l(0,1.000000,1.000000,0), r16.yyzw
      dp3 r32.x, r15.yzwy, r28.xyzx
      dp3 r32.y, r15.yzwy, r30.xyzx
      dp3 r32.z, r15.yzwy, r31.xyzx
      mad_sat r15.yzw, r32.xxyz, cb10[r7.w + 3].xxyz, l(0.000000, 0.500000, 0.500000, 0.500000)
      mul r32.xy, r15.yzyy, cb10[r7.w + 4].zwzz
      mul r32.z, r15.w, cb10[r7.w + 5].x
      add r15.yzw, r32.xxyz, cb10[r7.w + 5].yyzw
      dp3 r29.x, r12.xyzx, r28.xyzx
      dp3 r29.y, r12.xyzx, r30.xyzx
      dp3 r29.z, r12.xyzx, r31.xyzx
      lt r18.yzw, l(0.000000, 0.000000, 0.000000, 0.000000), r29.xxyz
      movc r20.z, r18.y, l(0), l(0.500000)
      add r27.xzw, r15.yyzw, r20.xxyz
      sample_l_indexable(texture3d)(float,float,float,float) r27.xzw, r27.xzwx, t17.xwyz, s4, l(0.000000)
      mul r28.xyz, r29.xyzx, r29.xyzx
      mul r28.xyz, r8.wwww, r28.xyzx
      movc r22.z, r18.z, l(0), l(0.500000)
      add r30.xyz, r15.yzwy, r22.xyzx
      sample_l_indexable(texture3d)(float,float,float,float) r30.xyz, r30.xyzx, t18.xyzw, s4, l(0.000000)
      mul r30.xyz, r28.yyyy, r30.xyzx
      mad r27.xzw, r27.xxzw, r28.xxxx, r30.xxyz
      movc r23.z, r18.w, l(0), l(0.500000)
      add r15.yzw, r15.yyzw, r23.xxyz
      sample_l_indexable(texture3d)(float,float,float,float) r15.yzw, r15.yzwy, t19.wxyz, s4, l(0.000000)
      mad r15.yzw, r15.yyzw, r28.zzzz, r27.xxzw
      sample_l_indexable(texturecubearray)(float,float,float,float) r18.yzw, r29.xyzw, t8.wxyz, s2, l(6.000000)
      and r27.xzw, r18.yyzw, l(0x7fffffff, 0, 0x7fffffff, 0x7fffffff)
      ieq r27.xzw, r27.xxzw, l(0x7f800000, 0, 0x7f800000, 0x7f800000)
      or r7.w, r27.z, r27.x
      or r7.w, r27.w, r7.w
      movc r18.yzw, r7.wwww, l(0,1.000000,1.000000,0), r18.yyzw
      mul r27.xzw, r15.yyzw, r18.yyzw
      dp3 r7.w, r27.xzwx, l(0.212600, 0.715200, 0.072200, 0.000000)
      mad r24.xyz, r15.yzwy, r18.yzwy, r24.xyzx
      mul r9.w, r3.w, r7.w
      mul r15.yzw, r8.wwww, r16.yyzw
      dp3 r8.w, r15.yzwy, l(0.212600, 0.715200, 0.072200, 0.000000)
      mad r7.w, r3.w, r7.w, r8.w
      div r7.w, r9.w, r7.w
      mov r28.x, r24.w
      mov r28.yz, r25.xxyx
      mad r15.yzw, r15.yyzw, r7.wwww, r28.xxyz
      mov r24.w, r15.y
      mov r25.xy, r15.zwzz
    else 
      mov r26.xyz, r25.xyzx
      mov r25.xyzw, r26.xyzw
    endif 
  endif 
  iadd r6.w, r6.w, l(1)
endloop 
mov r18.x, l(16)
mov r19.yz, l(0,0,1.000000,0)
mov r20.xy, l(0,0,0,0)
mov r22.xy, l(0,0,0,0)
mov r23.xy, l(0,0,0,0)
mov r15.yzw, r24.xxyz
mov r26.x, r24.w
mov r26.yz, r25.xxyx
mov r16.yz, r25.zzwz
mov r6.w, l(0)
loop 
  ieq r7.w, r6.w, l(2)
  breakc_nz r7.w
  movc r7.w, r6.w, r0.x, r13.z
  ult r8.w, r7.w, r4.z
  if_nz r8.w
    imul null, r7.w, r7.w, l(14)
    if_nz r2.z
      and r8.w, r16.z, l(15)
      imad r8.w, r8.w, l(20), l(880)
      add r18.yzw, cb1[24].xxyz, cb10[r7.w + 0].xxyz
      store_structured u2.xyzw, cb2[52].x, r8.w, r18.xyzw
    endif 
    iadd r21.y, r16.z, l(1)
    add r18.yzw, r11.xxyz, -cb10[r7.w + 0].xxyz
    and r8.w, l(0x0000ffff), cb10[r7.w + 7].z
    ubfe r9.w, l(6), l(25), cb10[r7.w + 7].z
    imul null, r10.w, r8.w, l(6)
    dp3 r14.w, cb11[r10.w + 0].xyzx, r18.yzwy
    add_sat r14.w, r14.w, cb11[r10.w + 0].w
    dp3 r16.w, cb11[r10.w + 1].xyzx, r18.yzwy
    add_sat r16.w, r16.w, cb11[r10.w + 1].w
    mul r14.w, r14.w, r16.w
    dp3 r16.w, cb11[r10.w + 2].xyzx, r18.yzwy
    add_sat r16.w, r16.w, cb11[r10.w + 2].w
    mul r14.w, r14.w, r16.w
    dp3 r16.w, cb11[r10.w + 3].xyzx, r18.yzwy
    add_sat r16.w, r16.w, cb11[r10.w + 3].w
    mul r14.w, r14.w, r16.w
    dp3 r16.w, cb11[r10.w + 4].xyzx, r18.yzwy
    add_sat r16.w, r16.w, cb11[r10.w + 4].w
    mul r14.w, r14.w, r16.w
    dp3 r16.w, cb11[r10.w + 5].xyzx, r18.yzwy
    add_sat r10.w, r16.w, cb11[r10.w + 5].w
    mul r19.x, r10.w, r14.w
    and r10.w, l(1), cb10[r7.w + 6].x
    movc r19.xw, r10.wwww, r19.xxxy, r19.zzzx
    mov r10.w, cb10[r7.w + 6].x
    mov r27.xy, r19.xwxx
    mov r14.w, l(1)
    loop 
      ige r16.w, r14.w, r9.w
      breakc_nz r16.w
      iadd r16.w, r8.w, r14.w
      imul null, r16.w, r16.w, l(6)
      dp3 r20.w, cb11[r16.w + 0].xyzx, r18.yzwy
      add_sat r20.w, r20.w, cb11[r16.w + 0].w
      mul r20.w, r20.w, r27.x
      dp3 r22.w, cb11[r16.w + 1].xyzx, r18.yzwy
      add_sat r22.w, r22.w, cb11[r16.w + 1].w
      mul r20.w, r20.w, r22.w
      dp3 r22.w, cb11[r16.w + 2].xyzx, r18.yzwy
      add_sat r22.w, r22.w, cb11[r16.w + 2].w
      mul r20.w, r20.w, r22.w
      dp3 r22.w, cb11[r16.w + 3].xyzx, r18.yzwy
      add_sat r22.w, r22.w, cb11[r16.w + 3].w
      mul r20.w, r20.w, r22.w
      dp3 r22.w, cb11[r16.w + 4].xyzx, r18.yzwy
      add_sat r22.w, r22.w, cb11[r16.w + 4].w
      mul r20.w, r20.w, r22.w
      dp3 r22.w, cb11[r16.w + 5].xyzx, r18.yzwy
      add_sat r16.w, r22.w, cb11[r16.w + 5].w
      mul r27.x, r16.w, r20.w
      ushr r22.w, r10.w, l(2)
      ubfe r23.w, l(1), l(2), r10.w
      and r26.w, r22.w, l(2)
      max r27.z, r27.x, r27.y
      mad r16.w, -r20.w, r16.w, l(1.000000)
      mul r16.w, r16.w, r27.y
      movc r21.w, r26.w, r16.w, r27.z
      movc r27.xy, r23.wwww, r27.xyxx, r21.zwzz
      iadd r14.w, r14.w, l(1)
      mov r10.w, r22.w
    endloop 
    add_sat r8.w, -r25.z, r27.y
    mul r9.w, r8.w, cb10[r7.w + 6].y
    lt r10.w, l(0.000000), r9.w
    if_nz r10.w
      and r10.w, r21.y, l(31)
      iadd r14.w, r10.w, l(-1)
      ult r14.w, r14.w, l(32)
      and r14.w, r2.z, r14.w
      if_nz r14.w
        imad r19.xw, r10.wwww, l(20, 0, 0, 20), l(860, 0, 0, 876)
        ld_structured_indexable(structured_buffer, stride=1792)(mixed,mixed,mixed,mixed) r10.w, cb2[52].x, r19.x, u2.xxxx
        or r10.w, r10.w, l(32)
        store_structured u2.x, cb2[52].x, r19.x, r10.w
        store_structured u2.x, cb2[52].x, r19.w, r9.w
      endif 
      iadd r16.z, r16.z, l(257)
      mad r16.y, r8.w, cb10[r7.w + 6].y, r16.y
      mul r8.w, r9.w, cb10[r7.w + 7].y
      mov r28.x, cb10[r7.w + 7].w
      mov r28.yz, cb10[r7.w + 8].xxyx
      dp3 r9.w, r17.xyzx, r28.xyzx
      dp3 r10.w, r18.yzwy, r28.xyzx
      add r10.w, r10.w, -cb10[r7.w + 8].z
      ge r14.w, r10.w, l(0.000000)
      max r10.w, r3.z, |r10.w|
      movc r10.w, r14.w, r10.w, -r10.w
      max r9.w, -r9.w, l(0.00000010)
      div r9.w, r10.w, r9.w
      min r9.w, |r9.w|, l(131072.000000)
      mov r28.x, cb10[r7.w + 8].w
      mov r28.yz, cb10[r7.w + 9].xxyx
      dp3 r10.w, r17.xyzx, r28.xyzx
      dp3 r14.w, r18.yzwy, r28.xyzx
      add r14.w, r14.w, -cb10[r7.w + 9].z
      ge r16.w, r14.w, l(0.000000)
      max r14.w, r3.z, |r14.w|
      movc r14.w, r16.w, r14.w, -r14.w
      max r10.w, -r10.w, l(0.00000010)
      div r10.w, r14.w, r10.w
      min r9.w, r9.w, |r10.w|
      mov r28.x, cb10[r7.w + 9].w
      mov r28.yz, cb10[r7.w + 10].xxyx
      dp3 r10.w, r17.xyzx, r28.xyzx
      dp3 r14.w, r18.yzwy, r28.xyzx
      add r14.w, r14.w, -cb10[r7.w + 10].z
      ge r16.w, r14.w, l(0.000000)
      max r14.w, r3.z, |r14.w|
      movc r14.w, r16.w, r14.w, -r14.w
      max r10.w, -r10.w, l(0.00000010)
      div r10.w, r14.w, r10.w
      min r9.w, r9.w, |r10.w|
      mov r28.x, cb10[r7.w + 10].w
      mov r28.yz, cb10[r7.w + 11].xxyx
      dp3 r10.w, r17.xyzx, r28.xyzx
      dp3 r14.w, r18.yzwy, r28.xyzx
      add r14.w, r14.w, -cb10[r7.w + 11].z
      ge r16.w, r14.w, l(0.000000)
      max r14.w, r3.z, |r14.w|
      movc r14.w, r16.w, r14.w, -r14.w
      max r10.w, -r10.w, l(0.00000010)
      div r10.w, r14.w, r10.w
      min r9.w, r9.w, |r10.w|
      mov r28.x, cb10[r7.w + 11].w
      mov r28.yz, cb10[r7.w + 12].xxyx
      dp3 r10.w, r17.xyzx, r28.xyzx
      dp3 r14.w, r18.yzwy, r28.xyzx
      add r14.w, r14.w, -cb10[r7.w + 12].z
      ge r16.w, r14.w, l(0.000000)
      max r14.w, r3.z, |r14.w|
      movc r14.w, r16.w, r14.w, -r14.w
      max r10.w, -r10.w, l(0.00000010)
      div r10.w, r14.w, r10.w
      min r9.w, r9.w, |r10.w|
      mov r28.x, cb10[r7.w + 12].w
      mov r28.yz, cb10[r7.w + 13].xxyx
      dp3 r10.w, r17.xyzx, r28.xyzx
      dp3 r14.w, r18.yzwy, r28.xyzx
      add r14.w, r14.w, -cb10[r7.w + 13].z
      ge r16.w, r14.w, l(0.000000)
      max r14.w, r3.z, |r14.w|
      movc r14.w, r16.w, r14.w, -r14.w
      max r10.w, -r10.w, l(0.00000010)
      div r10.w, r14.w, r10.w
      min r9.w, r9.w, |r10.w|
      add r28.x, r18.y, cb10[r7.w + 3].w
      add r28.yz, r18.zzwz, cb10[r7.w + 4].xxyx
      mad r27.xzw, r17.xxyz, r9.wwww, r28.xxyz
      dp3 r10.w, r27.xzwx, r27.xzwx
      sqrt r10.w, r10.w
      div r9.w, r9.w, r10.w
      add r9.w, r9.w, r9.w
      sqrt r9.w, r9.w
      mad r9.w, r2.w, l(5.000000), r9.w
      add r9.w, r9.w, l(-0.844800)
      mov r28.x, cb10[r7.w + 0].w
      mov r28.y, cb10[r7.w + 1].z
      mov r28.z, cb10[r7.w + 2].y
      dp3 r29.x, r27.xzwx, r28.xyzx
      mov r30.xy, cb10[r7.w + 1].xwxx
      mov r30.z, cb10[r7.w + 2].z
      dp3 r29.y, r27.xzwx, r30.xyzx
      mov r31.x, cb10[r7.w + 1].y
      mov r31.yz, cb10[r7.w + 2].xxwx
      dp3 r29.z, r27.xzwx, r31.xyzx
      ubfe r10.w, l(9), l(16), cb10[r7.w + 7].z
      utof r29.w, r10.w
      sample_l_indexable(texturecubearray)(float,float,float,float) r27.xzw, r29.xyzw, t8.xwyz, s2, r9.w
      and r32.xyz, r27.xzwx, l(0x7fffffff, 0x7fffffff, 0x7fffffff, 0)
      ieq r32.xyz, r32.xyzx, l(0x7f800000, 0x7f800000, 0x7f800000, 0)
      or r9.w, r32.y, r32.x
      or r9.w, r32.z, r9.w
      movc r27.xzw, r9.wwww, l(1.000000,0,1.000000,0), r27.xxzw
      dp3 r32.x, r18.yzwy, r28.xyzx
      dp3 r32.y, r18.yzwy, r30.xyzx
      dp3 r32.z, r18.yzwy, r31.xyzx
      mad_sat r18.yzw, r32.xxyz, cb10[r7.w + 3].xxyz, l(0.000000, 0.500000, 0.500000, 0.500000)
      mul r32.xy, r18.yzyy, cb10[r7.w + 4].zwzz
      mul r32.z, r18.w, cb10[r7.w + 5].x
      add r18.yzw, r32.xxyz, cb10[r7.w + 5].yyzw
      dp3 r29.x, r12.xyzx, r28.xyzx
      dp3 r29.y, r12.xyzx, r30.xyzx
      dp3 r29.z, r12.xyzx, r31.xyzx
      lt r28.xyz, l(0.000000, 0.000000, 0.000000, 0.000000), r29.xyzx
      movc r20.z, r28.x, l(0), l(0.500000)
      add r30.xyz, r18.yzwy, r20.xyzx
      sample_l_indexable(texture3d)(float,float,float,float) r30.xyz, r30.xyzx, t17.xyzw, s4, l(0.000000)
      mul r31.xyz, r29.xyzx, r29.xyzx
      mul r31.xyz, r8.wwww, r31.xyzx
      movc r22.z, r28.y, l(0), l(0.500000)
      add r28.xyw, r18.yzyw, r22.xyxz
      sample_l_indexable(texture3d)(float,float,float,float) r28.xyw, r28.xywx, t18.xywz, s4, l(0.000000)
      mul r28.xyw, r31.yyyy, r28.xyxw
      mad r28.xyw, r30.xyxz, r31.xxxx, r28.xyxw
      movc r23.z, r28.z, l(0), l(0.500000)
      add r18.yzw, r18.yyzw, r23.xxyz
      sample_l_indexable(texture3d)(float,float,float,float) r18.yzw, r18.yzwy, t19.wxyz, s4, l(0.000000)
      mad r18.yzw, r18.yyzw, r31.zzzz, r28.xxyw
      sample_l_indexable(texturecubearray)(float,float,float,float) r28.xyz, r29.xyzw, t8.xyzw, s2, l(6.000000)
      and r29.xyz, r28.xyzx, l(0x7fffffff, 0x7fffffff, 0x7fffffff, 0)
      ieq r29.xyz, r29.xyzx, l(0x7f800000, 0x7f800000, 0x7f800000, 0)
      or r7.w, r29.y, r29.x
      or r7.w, r29.z, r7.w
      movc r28.xyz, r7.wwww, l(1.000000,1.000000,0,0), r28.xyzx
      mul r29.xyz, r18.yzwy, r28.xyzx
      dp3 r7.w, r29.xyzx, l(0.212600, 0.715200, 0.072200, 0.000000)
      mad r15.yzw, r18.yyzw, r28.xxyz, r15.yyzw
      mul r9.w, r3.w, r7.w
      mul r18.yzw, r8.wwww, r27.xxzw
      dp3 r8.w, r18.yzwy, l(0.212600, 0.715200, 0.072200, 0.000000)
      mad r7.w, r3.w, r7.w, r8.w
      div r7.w, r9.w, r7.w
      mad r26.xyz, r18.yzwy, r7.wwww, r26.xyzx
    else 
      mov r21.x, r16.y
      mov r16.yz, r21.xxyx
    endif 
  endif 
  iadd r6.w, r6.w, l(1)
endloop 
ge r0.x, r25.z, l(1.000000)
bfi r2.w, l(8), l(0), r16.z, r25.w
movc r0.x, r0.x, r2.w, r16.z
max r2.w, r16.y, l(1.000000)
rcp r2.w, r2.w
mov_sat r16.y, r16.y
mul r18.xyz, r2.wwww, r15.yzwy
mul r19.xyz, r2.wwww, r26.xyzx
lt r3.z, r16.y, l(0.990000)
if_nz r3.z
  iadd r0.x, r0.x, l(256)
  add r3.z, -r16.y, l(1.000000)
  mul r3.w, r3.z, cb2[19].x
  add r16.yzw, r11.xxyz, -cb2[35].xxyz
  mul r20.x, r16.y, cb2[35].w
  mul r20.yz, r16.zzwz, cb2[36].xxyx
  add_sat r16.yzw, r20.xxyz, l(0.000000, 0.500000, 0.500000, 0.500000)
  mul r20.xy, r16.yzyy, cb2[36].zwzz
  mul r20.z, r16.w, cb2[37].x
  add r16.yzw, r20.xxyz, cb2[37].yyzw
  lt r20.xyz, l(0.000000, 0.000000, 0.000000, 0.000000), r12.xyzx
  movc r20.xyz, r20.xyzx, l(0,0,0,0), l(0.500000,0.500000,0.500000,0)
  mov r20.w, l(0)
  add r21.xyz, r16.yzwy, r20.wwxw
  sample_l_indexable(texture3d)(float,float,float,float) r21.xyz, r21.xyzx, t17.xyzw, s4, l(0.000000)
  mul r22.xyz, r12.xyzx, r12.xyzx
  mul r22.xyz, r3.wwww, r22.xyzx
  add r23.xyz, r16.yzwy, r20.wwyw
  sample_l_indexable(texture3d)(float,float,float,float) r23.xyz, r23.xyzx, t18.xyzw, s4, l(0.000000)
  mul r23.xyz, r22.yyyy, r23.xyzx
  mad r21.xyz, r21.xyzx, r22.xxxx, r23.xyzx
  add r16.yzw, r16.yyzw, r20.wwwz
  sample_l_indexable(texture3d)(float,float,float,float) r16.yzw, r16.yzwy, t19.wxyz, s4, l(0.000000)
  mad r16.yzw, r16.yyzw, r22.zzzz, r21.xxyz
  mov r12.w, l(0)
  sample_l_indexable(texturecubearray)(float,float,float,float) r20.xyz, r12.xyzw, t8.xyzw, s2, l(6.000000)
  mul r16.yzw, r16.yyzw, r20.xxyz
  dp3 r3.w, r16.yzwy, l(0.212600, 0.715200, 0.072200, 0.000000)
  mad r18.xyz, r15.yzwy, r2.wwww, r16.yzwy
  mov r17.w, l(0)
  sample_l_indexable(texturecubearray)(float,float,float,float) r15.yzw, r17.xyzw, t8.wxyz, s2, r3.y
  mad r2.w, cb2[19].x, r3.z, -r3.w
  mad r2.w, r2.y, r2.w, r3.w
  mad r19.xyz, r15.yzwy, r2.wwww, r19.xyzx
endif 
add r2.w, r5.z, r2.x
log r2.w, |r2.w|
mul r2.w, r1.w, r2.w
exp r2.w, r2.w
add r2.w, r5.z, r2.w
add_sat r2.w, r2.w, l(-1.000000)
mul r3.yzw, r5.zzzz, r18.xxyz
mad r15.yz, r2.xxyx, l(0.000000, 0.984375, 0.984375, 0.000000), l(0.000000, 0.00781250, 0.00781250, 0.000000)
sample_l_indexable(texture2d)(float,float,float,float) r15.yz, r15.yzyy, t5.zxyw, s2, l(0.000000)
mul r16.yzw, r2.wwww, r19.xxyz
mul r18.xyz, r15.yyyy, r16.yzwy
mul r15.yzw, r15.zzzz, r16.yyzw
sqrt r2.y, r1.w
mad r2.y, r2.y, l(0.500000), l(0.500000)
mul r2.y, r2.y, r2.y
mul r2.w, r2.y, l(0.500000)
mad r2.y, -r2.y, l(0.500000), l(1.000000)
mad r4.z, r2.x, r2.y, r2.w
mul r2.yw, r2.yyyw, r4.zzzz
mov r19.x, -r13.x
not r4.z, r3.x
mad r2.x, -r2.x, l(0.500000), l(1.000000)
mov r20.x, l(2)
mov r21.x, l(2)
mov r22.w, l(1.000000)
mov r19.z, r13.x
mov r23.w, l(1.000000)
mov r24.z, l(1.000000)
mov r25.w, l(1.000000)
mov r19.yw, r14.xxxx
mov r13.y, r19.w
mov r26.w, l(1.000000)
mov r14.y, r19.x
mov r14.z, r13.x
mov r27.w, l(1.000000)
mov r28.x, r14.x
mov r28.y, r19.x
mov r28.z, r13.x
mov r29.x, r14.x
mov r29.y, r19.x
mov r29.z, r13.x
mov r30.x, r14.x
mov r30.y, r19.x
mov r30.z, r13.x
mov r16.yzw, r3.yyzw
mov r31.xyz, r18.xyzx
mov r32.xyz, r15.yzwy
mov r5.z, l(0)
mov r6.w, l(0)
loop 
  ieq r7.w, r6.w, l(2)
  breakc_nz r7.w
  movc r7.w, r6.w, r0.y, r13.w
  imul null, r7.w, r7.w, l(15)
  ubfe r8.w, l(3), l(24), cb9[r7.w + 1].w
  switch r8.w
    case l(4)
    if_nz r2.z
      and r8.w, r5.z, l(3)
      imad r8.w, r8.w, l(24), l(112)
      add r20.yzw, cb1[24].xxyz, cb9[r7.w + 0].xxyz
      store_structured u2.xyzw, cb2[52].x, r8.w, r20.xyzw
    endif 
    iadd r8.w, r5.z, l(1)
    lt r9.w, l(0.000000), cb9[r7.w + 6].y
    mov r33.xy, cb9[r7.w + 5].zwzz
    mov r33.z, cb9[r7.w + 6].x
    mad r20.yzw, -r33.xxyz, l(0.000000, 0.500000, 0.500000, 0.500000), cb9[r7.w + 0].xxyz
    add r34.xyz, -r11.xyzx, r20.yzwy
    dp3 r10.w, r33.xyzx, r34.xyzx
    div_sat r12.w, -r10.w, cb9[r7.w + 6].y
    mad r35.xyz, r12.wwww, r33.xyzx, r20.yzwy
    movc r35.xyz, r9.wwww, r35.xyzx, cb9[r7.w + 0].xyzx
    add r35.xyz, -r11.xyzx, r35.xyzx
    dp3 r13.z, r35.xyzx, r35.xyzx
    rsq r14.w, r13.z
    mul r35.xyz, r14.wwww, r35.xyzx
    dp3 r14.w, r12.xyzx, r35.xyzx
    mov_sat r17.w, r14.w
    lt r18.w, l(0.000000), r17.w
    if_nz r18.w
      sqrt r18.w, r13.z
      mul r24.w, cb9[r7.w + 3].x, cb9[r7.w + 3].x
      div r13.z, r24.w, r13.z
      min r13.z, r13.z, l(1.000000)
      mad_sat r35.xy, r18.wwww, cb9[r7.w + 2].xzxx, cb9[r7.w + 2].ywyy
      mul r35.zw, r35.xxxy, r35.xxxy
      mad r35.xy, r35.xyxx, l(-2.000000, -2.000000, 0.000000, 0.000000), l(3.000000, 3.000000, 0.000000, 0.000000)
      mul r35.xy, r35.xyxx, r35.zwzz
      mul r13.z, r13.z, r35.x
      mul r13.z, r35.y, r13.z
      lt r18.w, l(0.000000), r13.z
      if_nz r18.w
        ubfe r18.w, l(3), l(27), cb9[r7.w + 1].w
        and r24.w, r8.w, l(7)
        iadd r28.w, r24.w, l(-1)
        ult r28.w, r28.w, l(32)
        and r28.w, r2.z, r28.w
        if_nz r28.w
          imad r35.xy, r24.wwww, l(24, 24, 0, 0), l(88, 104, 0, 0)
          ld_structured_indexable(structured_buffer, stride=1792)(mixed,mixed,mixed,mixed) r24.w, cb2[52].x, r35.x, u2.xxxx
          or r24.w, r24.w, l(4)
          store_structured u2.x, cb2[52].x, r35.x, r24.w
          store_structured u2.x, cb2[52].x, r35.y, r13.z
        endif 
        iadd r24.w, r5.z, l(257)
        ine r18.w, r18.w, l(1)
        if_nz r18.w
          mad r18.w, |r14.w|, l(-0.200000), l(0.400000)
          mad r35.xyz, r12.xyzx, r18.wwww, r11.xyzx
          add r35.xyz, r35.xyzx, -cb9[r7.w + 4].yzwy
          max r18.w, |r35.z|, |r35.y|
          max r18.w, r18.w, |r35.x|
          div r18.w, cb9[r7.w + 5].x, r18.w
          add r18.w, r18.w, cb9[r7.w + 5].y
          dp3 r28.w, r35.xyzx, r35.xyzx
          rsq r28.w, r28.w
          max r18.w, r18.w, l(0.00006104)
          and r29.w, l(0x0000ffff), cb9[r7.w + 1].w
          utof r36.w, r29.w
          mov r29.w, l(0)
          mov r30.w, l(0)
          loop 
            ige r31.w, r30.w, l(8)
            breakc_nz r31.w
            dp2 r37.y, icb[r30.w + 0].yxyy, r19.xyxx
            dp2 r37.z, icb[r30.w + 0].yxyy, r19.yzyy
            mul r37.yz, r37.yyzy, cb9[r7.w + 3].yyyy
            mul r37.x, r16.x, r37.y
            mul r37.w, r15.x, r37.y
            mad r36.xyz, r35.xyzx, r28.wwww, r37.xzwx
            sample_c_lz_indexable(texturecubearray)(float,float,float,float) r31.w, r36.xyzw, t10.xxxx, s13, r18.w
            mad r29.w, r31.w, l(0.125000), r29.w
            iadd r30.w, r30.w, l(1)
          endloop 
        else 
          mov r29.w, l(1.000000)
        endif 
        mul r13.z, r13.z, r29.w
        lt r18.w, l(0.000000), r13.z
        if_nz r18.w
          mul r18.w, r1.z, cb9[r7.w + 1].z
          mul r18.w, r18.w, l(0.250000)
          dp3 r28.w, r33.xyzx, r17.xyzx
          dp3 r30.w, r17.xyzx, r34.xyzx
          mad r31.w, -r28.w, r28.w, cb9[r7.w + 6].y
          mad r10.w, r28.w, r30.w, -r10.w
          div_sat r10.w, r10.w, r31.w
          div r28.w, r31.w, cb9[r7.w + 6].y
          mul r28.w, r28.w, l(10.000000)
          min r28.w, r28.w, l(1.000000)
          add r10.w, -r12.w, r10.w
          mad r10.w, r28.w, r10.w, r12.w
          mad r20.yzw, r10.wwww, r33.xxyz, r20.yyzw
          movc r20.yzw, r9.wwww, r20.yyzw, cb9[r7.w + 0].xxyz
          add r20.yzw, -r11.xxyz, r20.yyzw
          dp3 r9.w, r20.yzwy, r20.yzwy
          rsq r9.w, r9.w
          mul r33.xyz, r9.wwww, r20.yzwy
          ubfe r10.w, l(4), l(16), cb9[r7.w + 1].w
          ult r12.w, l(0), r10.w
          and r12.w, r3.x, r12.w
          if_nz r12.w
            iadd r10.w, r10.w, cb2[0].x
            imad r10.w, r10.w, l(15), l(-15)
            mad r12.w, |r14.w|, l(-0.200000), l(0.400000)
            mad r22.xyz, r12.xyzx, r12.wwww, r11.xyzx
            mov r34.xyz, cb9[r10.w + 6].yzwy
            mov r34.w, cb9[r10.w + 7].x
            dp4 r12.w, r34.xyzw, r22.xyzw
            mov r34.xyz, cb9[r10.w + 7].yzwy
            mov r34.w, cb9[r10.w + 8].x
            dp4 r28.w, r34.xyzw, r22.xyzw
            lt r30.w, r28.w, r12.w
            if_z r30.w
              mov r34.xyz, cb9[r10.w + 4].yzwy
              mov r34.w, cb9[r10.w + 5].x
              dp4 r34.x, r34.xyzw, r22.xyzw
              mov r35.xyz, cb9[r10.w + 5].yzwy
              mov r35.w, cb9[r10.w + 6].x
              dp4 r34.y, r35.xyzw, r22.xyzw
              div r22.xy, r34.xyxx, r28.wwww
              mad r22.xy, r22.xyxx, l(0.500000, -0.500000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)
              add r34.x, r22.x, cb9[r10.w + 9].w
              add r34.y, r22.y, cb9[r10.w + 10].x
              mul r22.xy, r34.xyxx, cb9[r10.w + 9].yzyy
              div r34.xy, cb9[r10.w + 3].yyyy, cb9[r10.w + 8].ywyy
              add r34.zw, -r34.xxxy, l(0.000000, 0.000000, 1.000000, 1.000000)
              ge r34.zw, r22.xxxy, r34.zzzw
              ge r34.xy, r34.xyxx, r22.xyxx
              or r34.xy, r34.xyxx, r34.zwzz
              or r22.z, r34.y, r34.x
              if_z r22.z
                mov_sat r22.xy, r22.xyxx
                mad r34.x, r22.x, cb9[r10.w + 8].y, cb9[r10.w + 8].z
                mad r34.y, r22.y, cb9[r10.w + 8].w, cb9[r10.w + 9].x
                mul r22.x, r28.w, cb9[r10.w + 10].z
                mad r12.w, cb9[r10.w + 10].y, r28.w, r12.w
                div r12.w, r12.w, r22.x
              endif 
            else 
              mov r22.z, l(-1)
            endif 
            or r22.x, r30.w, r22.z
            if_z r22.x
              max r12.w, r12.w, l(0.00006104)
              and r22.x, l(0x0000ffff), cb9[r10.w + 1].w
              if_nz cb2[58].y
                utof r35.z, r22.x
                mov r22.yz, l(0,0,0,0)
                loop 
                  ige r28.w, r22.z, l(8)
                  breakc_nz r28.w
                  dp2 r36.x, icb[r22.z + 0].yxyy, r19.xwxx
                  dp2 r36.y, icb[r22.z + 0].xyxx, r13.xyxx
                  mad r35.xy, r36.xyxx, cb9[r10.w + 3].yyyy, r34.xyxx
                  sample_c_lz_indexable(texture2darray)(float,float,float,float) r28.w, r35.xyzx, t9.xxxx, s13, r12.w
                  mad r22.y, r28.w, l(0.125000), r22.y
                  iadd r22.z, r22.z, l(1)
                endloop 
              else 
                utof r34.z, r22.x
                sample_c_lz_indexable(texture2darray)(float,float,float,float) r22.y, r34.xyzx, t9.xxxx, s13, r12.w
              endif 
              mul r10.w, r22.y, r22.y
              mul r10.w, r22.y, r10.w
            else 
              mov r10.w, l(1.000000)
            endif 
            mul r13.z, r10.w, r13.z
          else 
            ubfe r10.w, l(4), l(20), cb9[r7.w + 1].w
            ult r12.w, l(0), r10.w
            and r12.w, r4.z, r12.w
            if_nz r12.w
              iadd r10.w, r10.w, cb2[0].x
              imad r10.w, r10.w, l(15), l(-15)
              mad r12.w, |r14.w|, l(-0.200000), l(0.400000)
              mad r23.xyz, r12.xyzx, r12.wwww, r11.xyzx
              mov r34.xyz, cb9[r10.w + 6].yzwy
              mov r34.w, cb9[r10.w + 7].x
              dp4 r12.w, r34.xyzw, r23.xyzw
              mov r34.xyz, cb9[r10.w + 7].yzwy
              mov r34.w, cb9[r10.w + 8].x
              dp4 r22.x, r34.xyzw, r23.xyzw
              lt r22.z, r22.x, r12.w
              if_z r22.z
                mov r34.xyz, cb9[r10.w + 4].yzwy
                mov r34.w, cb9[r10.w + 5].x
                dp4 r34.x, r34.xyzw, r23.xyzw
                mov r35.xyz, cb9[r10.w + 5].yzwy
                mov r35.w, cb9[r10.w + 6].x
                dp4 r34.y, r35.xyzw, r23.xyzw
                div r23.xy, r34.xyxx, r22.xxxx
                mad r23.xy, r23.xyxx, l(0.500000, -0.500000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)
                add r34.x, r23.x, cb9[r10.w + 9].w
                add r34.y, r23.y, cb9[r10.w + 10].x
                mul r23.xy, r34.xyxx, cb9[r10.w + 9].yzyy
                div r34.xy, cb9[r10.w + 3].yyyy, cb9[r10.w + 8].ywyy
                add r34.zw, -r34.xxxy, l(0.000000, 0.000000, 1.000000, 1.000000)
                ge r34.zw, r23.xxxy, r34.zzzw
                ge r34.xy, r34.xyxx, r23.xyxx
                or r34.xy, r34.xyxx, r34.zwzz
                or r23.z, r34.y, r34.x
                if_z r23.z
                  mov_sat r23.xy, r23.xyxx
                  mad r34.x, r23.x, cb9[r10.w + 8].y, cb9[r10.w + 8].z
                  mad r34.y, r23.y, cb9[r10.w + 8].w, cb9[r10.w + 9].x
                  mul r23.x, r22.x, cb9[r10.w + 10].z
                  mad r12.w, cb9[r10.w + 10].y, r22.x, r12.w
                  div r12.w, r12.w, r23.x
                endif 
              else 
                mov r23.z, l(-1)
              endif 
              or r22.x, r22.z, r23.z
              if_z r22.x
                max r12.w, r12.w, l(0.00006104)
                and r22.x, l(0x0000ffff), cb9[r10.w + 1].w
                if_nz cb2[58].y
                  utof r23.z, r22.x
                  mov r22.z, l(0)
                  mov r28.w, l(0)
                  loop 
                    ige r30.w, r28.w, l(8)
                    breakc_nz r30.w
                    dp2 r35.x, icb[r28.w + 0].xyxx, r14.xyxx
                    dp2 r35.y, icb[r28.w + 0].yxyy, r14.xzxx
                    mad r23.xy, r35.xyxx, cb9[r10.w + 3].yyyy, r34.xyxx
                    sample_c_lz_indexable(texture2darray)(float,float,float,float) r23.x, r23.xyzx, t9.xxxx, s13, r12.w
                    mad r22.z, r23.x, l(0.125000), r22.z
                    iadd r28.w, r28.w, l(1)
                  endloop 
                else 
                  utof r34.z, r22.x
                  sample_c_lz_indexable(texture2darray)(float,float,float,float) r22.z, r34.xyzx, t9.xxxx, s13, r12.w
                endif 
                mul r10.w, r22.z, r22.z
                mul r10.w, r22.z, r10.w
              else 
                mov r10.w, l(1.000000)
              endif 
              mul r13.z, r10.w, r13.z
            endif 
          endif 
          mad r10.w, -r17.w, r2.x, l(1.000000)
          mul r10.w, r10.w, r10.w
          mad r10.w, -r10.w, l(0.620000), l(0.620000)
          add r10.w, -r17.w, r10.w
          mad r10.w, r1.w, r10.w, r17.w
          mul r10.w, r13.z, r10.w
          mov r23.x, cb9[r7.w + 0].w
          mov r23.yz, cb9[r7.w + 1].xxyx
          lt r12.w, l(0.000000), r14.w
          mad r34.xyz, r10.wwww, r23.xyzx, r16.yzwy
          dp3_sat r10.w, r12.xyzx, r33.xyzx
          mad r20.yzw, r20.yyzw, r9.wwww, r5.xxyw
          dp3 r9.w, r20.yzwy, r20.yzwy
          rsq r9.w, r9.w
          mul r20.yzw, r9.wwww, r20.yyzw
          dp3 r9.w, r20.yzwy, r5.xywx
          dp3 r14.w, r12.xyzx, r20.yzwy
          mad r17.w, |r14.w|, r1.z, -|r14.w|
          mad r14.w, |r14.w|, r17.w, l(1.000000)
          mad r17.w, r10.w, r2.y, r2.w
          mul r14.w, r14.w, r14.w
          mul r14.w, r17.w, r14.w
          rcp r14.w, r14.w
          mul r10.w, r18.w, r10.w
          mul r10.w, r10.w, r14.w
          mul r10.w, r13.z, r10.w
          mad r20.yzw, r10.wwww, r23.xxyz, r32.xxyz
          add_sat r9.w, -r9.w, l(1.000000)
          mul r14.w, r9.w, r9.w
          mul r14.w, r14.w, r14.w
          mul r9.w, r9.w, r14.w
          mul r9.w, r9.w, r10.w
          mad r23.xyz, r9.wwww, r23.xyzx, r31.xyzx
          movc r16.yzw, r12.wwww, r34.xxyz, r16.yyzw
          movc r31.xyz, r12.wwww, r23.xyzx, r31.xyzx
          movc r32.xyz, r12.wwww, r20.yzwy, r32.xyzx
          and r9.w, r24.w, l(7)
          iadd r10.w, r9.w, l(-1)
          ult r10.w, r10.w, l(32)
          and r10.w, r2.z, r10.w
          if_nz r10.w
            imad r20.yz, r9.wwww, l(0, 24, 24, 0), l(0, 88, 108, 0)
            ld_structured_indexable(structured_buffer, stride=1792)(mixed,mixed,mixed,mixed) r9.w, cb2[52].x, r20.y, u2.xxxx
            or r9.w, r9.w, l(8)
            store_structured u2.x, cb2[52].x, r20.y, r9.w
            store_structured u2.x, cb2[52].x, r20.z, r13.z
          endif 
          iadd r5.z, r5.z, l(0x00010101)
        else 
          mov r5.z, r24.w
        endif 
      else 
        mov r5.z, r8.w
      endif 
    else 
      mov r5.z, r8.w
    endif 
    break 
    case l(2)
    if_nz r2.z
      and r8.w, r5.z, l(3)
      imad r8.w, r8.w, l(24), l(112)
      add r21.yzw, cb1[24].xxyz, cb9[r7.w + 0].xxyz
      store_structured u2.xyzw, cb2[52].x, r8.w, r21.xyzw
    endif 
    iadd r8.w, r5.z, l(1)
    add r23.xy, -r11.xyxx, cb9[r7.w + 3].zwzz
    add r23.z, -r11.z, cb9[r7.w + 4].x
    dp3 r9.w, r23.xyzx, r23.xyzx
    rsq r9.w, r9.w
    mul r20.yzw, r9.wwww, r23.xxyz
    dp3 r10.w, r12.xyzx, r20.yzwy
    mov_sat r12.w, r10.w
    lt r13.z, l(0.000000), r12.w
    if_nz r13.z
      mov r33.xyz, cb9[r7.w + 7].yzwy
      mov r33.w, cb9[r7.w + 8].x
      dp4 r13.z, r33.xyzw, r11.xyzw
      lt r14.w, r13.z, l(1.000000)
      if_nz r14.w
        mov r20.yzw, l(0,1.000000,1.000000,1.000000)
        mov r14.w, l(0)
      else 
        add r21.yzw, -r11.xxyz, cb9[r7.w + 0].xxyz
        mul r17.w, cb9[r7.w + 3].x, cb9[r7.w + 3].x
        dp3 r18.w, r21.yzwy, r21.yzwy
        div r17.w, r17.w, r18.w
        min r17.w, r17.w, l(1.000000)
        mad_sat r21.yz, r13.zzzz, cb9[r7.w + 2].xxzx, cb9[r7.w + 2].yywy
        mul r34.xy, r21.yzyy, r21.yzyy
        mad r21.yz, r21.yyzy, l(0.000000, -2.000000, -2.000000, 0.000000), l(0.000000, 3.000000, 3.000000, 0.000000)
        mul r21.yz, r21.yyzy, r34.xxyx
        mul r17.w, r17.w, r21.y
        mul r17.w, r21.z, r17.w
        mov r34.xyz, cb9[r7.w + 4].yzwy
        mov r34.w, cb9[r7.w + 5].x
        dp4 r34.x, r34.xyzw, r11.xyzw
        mov r35.xyz, cb9[r7.w + 5].yzwy
        mov r35.w, cb9[r7.w + 6].x
        dp4 r34.y, r35.xyzw, r11.xyzw
        div r24.xy, r34.xyxx, r13.zzzz
        lt r13.z, cb9[r7.w + 10].w, l(0.00048828)
        if_nz r13.z
          mad_sat r21.yz, |r24.xxyx|, cb9[r7.w + 12].xxyx, cb9[r7.w + 12].zzwz
          mul r34.xy, r21.yzyy, r21.yzyy
          mad r21.yz, r21.yyzy, l(0.000000, -2.000000, -2.000000, 0.000000), l(0.000000, 3.000000, 3.000000, 0.000000)
          mul r21.yz, r21.yyzy, r34.xxyx
          mul r13.z, r21.z, r21.y
        else 
          mul_sat r34.xyzw, |r24.yyxx|, cb9[r7.w + 11].xyzw
          log r34.xyzw, r34.xyzw
          mul r34.xyzw, r34.xyzw, cb9[r7.w + 12].zzzz
          exp r34.xyzw, r34.xyzw
          add r21.yz, r34.zzwz, r34.xxyx
          log r21.yz, r21.yyzy
          mul r21.yz, r21.yyzy, cb9[r7.w + 12].wwww
          exp r21.yz, r21.yyzy
          mul r18.w, r21.y, cb9[r7.w + 12].x
          mad r21.y, cb9[r7.w + 12].y, r21.z, l(-1.000000)
          mad r18.w, cb9[r7.w + 12].y, r21.z, -r18.w
          div_sat r18.w, r21.y, r18.w
          mul r21.y, r18.w, r18.w
          mad r18.w, r18.w, l(-2.000000), l(3.000000)
          mul r13.z, r18.w, r21.y
        endif 
        mul r14.w, r13.z, r17.w
        and r13.z, l(255), cb9[r7.w + 14].w
        if_nz r13.z
          dp3 r17.w, cb9[r7.w + 13].xyzx, r24.xyzx
          mov r34.x, cb9[r7.w + 13].w
          mov r34.yz, cb9[r7.w + 14].xxyx
          dp3 r18.w, r34.xyzx, r24.xyzx
          frc r34.x, r17.w
          frc r34.y, r18.w
          iadd r13.z, r13.z, l(-1)
          utof r34.z, r13.z
          sample_l_indexable(texture2darray)(float,float,float,float) r20.yzw, r34.xyzx, t20.wxyz, s2, l(0.000000)
        else 
          mov r20.yzw, l(0,1.000000,1.000000,1.000000)
        endif 
      endif 
      mov r34.x, cb9[r7.w + 0].w
      mov r34.yz, cb9[r7.w + 1].xxyx
      mul r20.yzw, r20.yyzw, r34.xxyz
      lt r13.z, l(0.000000), r14.w
      if_nz r13.z
        ubfe r13.z, l(3), l(27), cb9[r7.w + 1].w
        and r17.w, r8.w, l(7)
        iadd r18.w, r17.w, l(-1)
        ult r18.w, r18.w, l(32)
        and r18.w, r2.z, r18.w
        if_nz r18.w
          imad r21.yz, r17.wwww, l(0, 24, 24, 0), l(0, 88, 104, 0)
          ld_structured_indexable(structured_buffer, stride=1792)(mixed,mixed,mixed,mixed) r17.w, cb2[52].x, r21.y, u2.xxxx
          or r17.w, r17.w, l(4)
          store_structured u2.x, cb2[52].x, r21.y, r17.w
          store_structured u2.x, cb2[52].x, r21.z, r14.w
        endif 
        iadd r17.w, r5.z, l(257)
        ine r13.z, r13.z, l(1)
        if_nz r13.z
          mad r13.z, |r10.w|, l(-0.200000), l(0.400000)
          mad r25.xyz, r12.xyzx, r13.zzzz, r11.xyzx
          mov r34.xyz, cb9[r7.w + 6].yzwy
          mov r34.w, cb9[r7.w + 7].x
          dp4 r13.z, r34.xyzw, r25.xyzw
          dp4 r18.w, r33.xyzw, r25.xyzw
          ge r21.y, r18.w, r13.z
          if_nz r21.y
            mov r33.xyz, cb9[r7.w + 4].yzwy
            mov r33.w, cb9[r7.w + 5].x
            dp4 r24.x, r33.xyzw, r25.xyzw
            mov r33.xyz, cb9[r7.w + 5].yzwy
            mov r33.w, cb9[r7.w + 6].x
            dp4 r24.y, r33.xyzw, r25.xyzw
            div r21.yz, r24.xxyx, r18.wwww
            mad_sat r21.yz, r21.yyzy, l(0.000000, 0.500000, -0.500000, 0.000000), l(0.000000, 0.500000, 0.500000, 0.000000)
            mad r25.x, r21.y, cb9[r7.w + 8].y, cb9[r7.w + 8].z
            mad r25.y, r21.z, cb9[r7.w + 8].w, cb9[r7.w + 9].x
            div r13.z, r13.z, r18.w
            max r13.z, r13.z, l(0.00006104)
            and r18.w, l(0x0000ffff), cb9[r7.w + 1].w
            if_nz cb2[58].y
              utof r33.z, r18.w
              mov r21.yz, l(0,0,0,0)
              loop 
                ige r21.w, r21.z, l(8)
                breakc_nz r21.w
                dp2 r24.x, icb[r21.z + 0].xyxx, r28.xyxx
                dp2 r24.y, icb[r21.z + 0].yxyy, r28.xzxx
                mad r33.xy, r24.xyxx, cb9[r7.w + 3].yyyy, r25.xyxx
                sample_c_lz_indexable(texture2darray)(float,float,float,float) r21.w, r33.xyzx, t9.xxxx, s13, r13.z
                mad r21.y, r21.w, l(0.125000), r21.y
                iadd r21.z, r21.z, l(1)
              endloop 
            else 
              utof r25.z, r18.w
              sample_c_lz_indexable(texture2darray)(float,float,float,float) r21.y, r25.xyzx, t9.xxxx, s13, r13.z
            endif 
            mul r13.z, r21.y, r21.y
            mul r13.z, r21.y, r13.z
          else 
            mov r13.z, l(1.000000)
          endif 
        else 
          mov r13.z, l(1.000000)
        endif 
        mul r13.z, r13.z, r14.w
        lt r14.w, l(0.000000), r13.z
        if_nz r14.w
          mul r14.w, r1.z, cb9[r7.w + 1].z
          mul r14.w, r12.w, r14.w
          ubfe r18.w, l(4), l(16), cb9[r7.w + 1].w
          ult r21.z, l(0), r18.w
          and r21.z, r3.x, r21.z
          if_nz r21.z
            iadd r18.w, r18.w, cb2[0].x
            imad r18.w, r18.w, l(15), l(-15)
            mad r21.z, |r10.w|, l(-0.200000), l(0.400000)
            mad r26.xyz, r12.xyzx, r21.zzzz, r11.xyzx
            mov r33.xyz, cb9[r18.w + 6].yzwy
            mov r33.w, cb9[r18.w + 7].x
            dp4 r21.z, r33.xyzw, r26.xyzw
            mov r33.xyz, cb9[r18.w + 7].yzwy
            mov r33.w, cb9[r18.w + 8].x
            dp4 r21.w, r33.xyzw, r26.xyzw
            lt r22.x, r21.w, r21.z
            if_z r22.x
              mov r33.xyz, cb9[r18.w + 4].yzwy
              mov r33.w, cb9[r18.w + 5].x
              dp4 r24.x, r33.xyzw, r26.xyzw
              mov r33.xyz, cb9[r18.w + 5].yzwy
              mov r33.w, cb9[r18.w + 6].x
              dp4 r24.y, r33.xyzw, r26.xyzw
              div r24.xy, r24.xyxx, r21.wwww
              mad r24.xy, r24.xyxx, l(0.500000, -0.500000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)
              add r25.x, r24.x, cb9[r18.w + 9].w
              add r25.y, r24.y, cb9[r18.w + 10].x
              mul r24.xy, r25.xyxx, cb9[r18.w + 9].yzyy
              div r25.xy, cb9[r18.w + 3].yyyy, cb9[r18.w + 8].ywyy
              add r26.xy, -r25.xyxx, l(1.000000, 1.000000, 0.000000, 0.000000)
              ge r26.xy, r24.xyxx, r26.xyxx
              ge r25.xy, r25.xyxx, r24.xyxx
              or r25.xy, r25.xyxx, r26.xyxx
              or r24.w, r25.y, r25.x
              if_z r24.w
                mov_sat r24.xy, r24.xyxx
                mad r25.x, r24.x, cb9[r18.w + 8].y, cb9[r18.w + 8].z
                mad r25.y, r24.y, cb9[r18.w + 8].w, cb9[r18.w + 9].x
                mul r24.x, r21.w, cb9[r18.w + 10].z
                mad r21.z, cb9[r18.w + 10].y, r21.w, r21.z
                div r21.z, r21.z, r24.x
              endif 
            else 
              mov r24.w, l(-1)
            endif 
            or r21.w, r22.x, r24.w
            if_z r21.w
              max r21.z, r21.z, l(0.00006104)
              and r21.w, l(0x0000ffff), cb9[r18.w + 1].w
              if_nz cb2[58].y
                utof r26.z, r21.w
                mov r22.x, l(0)
                mov r24.x, l(0)
                loop 
                  ige r24.y, r24.x, l(8)
                  breakc_nz r24.y
                  dp2 r33.x, icb[r24.x + 0].xyxx, r29.xyxx
                  dp2 r33.y, icb[r24.x + 0].yxyy, r29.xzxx
                  mad r26.xy, r33.xyxx, cb9[r18.w + 3].yyyy, r25.xyxx
                  sample_c_lz_indexable(texture2darray)(float,float,float,float) r24.y, r26.xyzx, t9.xxxx, s13, r21.z
                  mad r22.x, r24.y, l(0.125000), r22.x
                  iadd r24.x, r24.x, l(1)
                endloop 
              else 
                utof r25.z, r21.w
                sample_c_lz_indexable(texture2darray)(float,float,float,float) r22.x, r25.xyzx, t9.xxxx, s13, r21.z
              endif 
              mul r18.w, r22.x, r22.x
              mul r18.w, r22.x, r18.w
            else 
              mov r18.w, l(1.000000)
            endif 
            mul r13.z, r13.z, r18.w
          else 
            ubfe r7.w, l(4), l(20), cb9[r7.w + 1].w
            ult r18.w, l(0), r7.w
            and r18.w, r4.z, r18.w
            if_nz r18.w
              iadd r7.w, r7.w, cb2[0].x
              imad r7.w, r7.w, l(15), l(-15)
              mad r18.w, |r10.w|, l(-0.200000), l(0.400000)
              mad r27.xyz, r12.xyzx, r18.wwww, r11.xyzx
              mov r33.xyz, cb9[r7.w + 6].yzwy
              mov r33.w, cb9[r7.w + 7].x
              dp4 r18.w, r33.xyzw, r27.xyzw
              mov r33.xyz, cb9[r7.w + 7].yzwy
              mov r33.w, cb9[r7.w + 8].x
              dp4 r21.z, r33.xyzw, r27.xyzw
              lt r21.w, r21.z, r18.w
              if_z r21.w
                mov r33.xyz, cb9[r7.w + 4].yzwy
                mov r33.w, cb9[r7.w + 5].x
                dp4 r24.x, r33.xyzw, r27.xyzw
                mov r33.xyz, cb9[r7.w + 5].yzwy
                mov r33.w, cb9[r7.w + 6].x
                dp4 r24.y, r33.xyzw, r27.xyzw
                div r24.xy, r24.xyxx, r21.zzzz
                mad r24.xy, r24.xyxx, l(0.500000, -0.500000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)
                add r25.x, r24.x, cb9[r7.w + 9].w
                add r25.y, r24.y, cb9[r7.w + 10].x
                mul r24.xy, r25.xyxx, cb9[r7.w + 9].yzyy
                div r25.xy, cb9[r7.w + 3].yyyy, cb9[r7.w + 8].ywyy
                add r26.xy, -r25.xyxx, l(1.000000, 1.000000, 0.000000, 0.000000)
                ge r26.xy, r24.xyxx, r26.xyxx
                ge r25.xy, r25.xyxx, r24.xyxx
                or r25.xy, r25.xyxx, r26.xyxx
                or r24.w, r25.y, r25.x
                if_z r24.w
                  mov_sat r24.xy, r24.xyxx
                  mad r25.x, r24.x, cb9[r7.w + 8].y, cb9[r7.w + 8].z
                  mad r25.y, r24.y, cb9[r7.w + 8].w, cb9[r7.w + 9].x
                  mul r24.x, r21.z, cb9[r7.w + 10].z
                  mad r18.w, cb9[r7.w + 10].y, r21.z, r18.w
                  div r18.w, r18.w, r24.x
                endif 
              else 
                mov r24.w, l(-1)
              endif 
              or r21.z, r21.w, r24.w
              if_z r21.z
                max r18.w, r18.w, l(0.00006104)
                and r21.z, l(0x0000ffff), cb9[r7.w + 1].w
                if_nz cb2[58].y
                  utof r26.z, r21.z
                  mov r21.w, l(0)
                  mov r24.x, l(0)
                  loop 
                    ige r24.y, r24.x, l(8)
                    breakc_nz r24.y
                    dp2 r27.x, icb[r24.x + 0].xyxx, r30.xyxx
                    dp2 r27.y, icb[r24.x + 0].yxyy, r30.xzxx
                    mad r26.xy, r27.xyxx, cb9[r7.w + 3].yyyy, r25.xyxx
                    sample_c_lz_indexable(texture2darray)(float,float,float,float) r24.y, r26.xyzx, t9.xxxx, s13, r18.w
                    mad r21.w, r24.y, l(0.125000), r21.w
                    iadd r24.x, r24.x, l(1)
                  endloop 
                else 
                  utof r25.z, r21.z
                  sample_c_lz_indexable(texture2darray)(float,float,float,float) r21.w, r25.xyzx, t9.xxxx, s13, r18.w
                endif 
                mul r7.w, r21.w, r21.w
                mul r7.w, r21.w, r7.w
              else 
                mov r7.w, l(1.000000)
              endif 
              mul r13.z, r7.w, r13.z
            endif 
          endif 
          mad r7.w, -r12.w, r2.x, l(1.000000)
          mul r7.w, r7.w, r7.w
          mad r7.w, -r7.w, l(0.620000), l(0.620000)
          add r7.w, -r12.w, r7.w
          mad r7.w, r1.w, r7.w, r12.w
          mul r7.w, r13.z, r7.w
          lt r10.w, l(0.000000), r10.w
          mad r24.xyw, r7.wwww, r20.yzyw, r16.yzyw
          mad r23.xyz, r23.xyzx, r9.wwww, r5.xywx
          dp3 r7.w, r23.xyzx, r23.xyzx
          rsq r7.w, r7.w
          mul r23.xyz, r7.wwww, r23.xyzx
          dp3 r7.w, r23.xyzx, r5.xywx
          dp3 r9.w, r12.xyzx, r23.xyzx
          mad r18.w, |r9.w|, r1.z, -|r9.w|
          mad r9.w, |r9.w|, r18.w, l(1.000000)
          mad r12.w, r12.w, r2.y, r2.w
          mul r9.w, r9.w, r9.w
          mul r9.w, r12.w, r9.w
          rcp r9.w, r9.w
          mul r9.w, r14.w, r9.w
          mul r9.w, r9.w, r13.z
          mul r9.w, r9.w, l(0.250000)
          mad r23.xyz, r9.wwww, r20.yzwy, r32.xyzx
          add_sat r7.w, -r7.w, l(1.000000)
          mul r12.w, r7.w, r7.w
          mul r12.w, r12.w, r12.w
          mul r7.w, r7.w, r12.w
          mul r7.w, r7.w, r9.w
          mad r20.yzw, r7.wwww, r20.yyzw, r31.xxyz
          movc r16.yzw, r10.wwww, r24.xxyw, r16.yyzw
          movc r31.xyz, r10.wwww, r20.yzwy, r31.xyzx
          movc r32.xyz, r10.wwww, r23.xyzx, r32.xyzx
          and r7.w, r17.w, l(7)
          iadd r9.w, r7.w, l(-1)
          ult r9.w, r9.w, l(32)
          and r9.w, r2.z, r9.w
          if_nz r9.w
            imad r20.yz, r7.wwww, l(0, 24, 24, 0), l(0, 88, 108, 0)
            ld_structured_indexable(structured_buffer, stride=1792)(mixed,mixed,mixed,mixed) r7.w, cb2[52].x, r20.y, u2.xxxx
            or r7.w, r7.w, l(8)
            store_structured u2.x, cb2[52].x, r20.y, r7.w
            store_structured u2.x, cb2[52].x, r20.z, r13.z
          endif 
          iadd r5.z, r5.z, l(0x00010101)
        else 
          mov r5.z, r17.w
        endif 
      else 
        mov r5.z, r8.w
      endif 
    else 
      mov r5.z, r8.w
    endif 
    break 
    default 
    break 
  endswitch 
  iadd r6.w, r6.w, l(1)
endloop 
mad r3.xyz, r4.xwyx, l(1.000000, 3.000000, 2.000000, 0.000000), l(0.000000, 0.500000, -1.000000, 0.000000)
ftou r0.y, r3.y
mad r2.xyw, r7.zxzy, l(3.000000, 1.000000, 0.000000, 2.000000), l(0.500000, 0.000000, 0.000000, -1.000000)
ftou r1.z, r2.x
ieq r1.z, r0.y, r1.z
movc r1.zw, r1.zzzz, r2.yyyw, l(0,0,-1.000000,0)
mad r2.xyw, r8.zxzy, l(3.000000, 1.000000, 0.000000, 2.000000), l(0.500000, 0.000000, 0.000000, -1.000000)
ftou r2.x, r2.x
ieq r2.x, r0.y, r2.x
movc r2.xy, r2.xxxx, r2.ywyy, l(-1.000000,0,0,0)
mad r4.xyz, r9.zxyz, l(3.000000, 1.000000, 2.000000, 0.000000), l(0.500000, 0.000000, -1.000000, 0.000000)
ftou r2.w, r4.x
ieq r2.w, r0.y, r2.w
movc r4.xy, r2.wwww, r4.yzyy, l(-1.000000,0,0,0)
mad r5.xyw, r10.zxzy, l(3.000000, 1.000000, 0.000000, 2.000000), l(0.500000, 0.000000, 0.000000, -1.000000)
ftou r2.w, r5.x
ieq r0.y, r0.y, r2.w
movc r4.zw, r0.yyyy, r5.yyyw, l(0,0,-1.000000,0)
mov r7.x, r1.z
mov r7.y, r2.x
mov r7.zw, r4.xxxz
add r7.xyzw, -r3.xxxx, r7.xyzw
ge r7.xyzw, |r7.xyzw|, l(0.00902149, 0.00902149, 0.00902149, 0.00902149)
movc r7.xyzw, r7.xyzw, l(0,0,0,0), l(1.000000,1.000000,1.000000,1.000000)
add r0.y, r7.y, r7.x
add r0.y, r7.z, r0.y
add r0.y, r7.w, r0.y
mul r1.z, r2.y, r7.y
mad r1.z, r7.x, r1.w, r1.z
mad r1.z, r7.z, r4.y, r1.z
mad r1.z, r7.w, r4.w, r1.z
div r3.w, r1.z, r0.y
ge r0.y, l(0.000000), r0.y
movc r3.yz, r0.yyyy, l(0,0,0,0), r3.zzwz
and r1.zw, r1.xxxy, l(0, 0, 1, 1)
ieq r0.y, r1.w, r1.z
movc r2.xyw, r0.yyyy, r3.xyxz, r3.xzxy
mad r0.y, -r2.w, l(0.500000), r2.x
add r3.y, r0.y, r2.w
mad r3.z, -r2.y, l(0.500000), r0.y
add r3.x, r2.y, r3.z
add r2.xyw, -r3.xyxz, l(1.000000, 1.000000, 0.000000, 1.000000)
mul r2.xyw, r2.xyxw, r31.xyxz
mad r2.xyw, r32.xyxz, r3.xyxz, r2.xyxw
mad r2.xyw, r16.yzyw, r6.xyxz, r2.xyxw
lt r0.y, l(0.000000), cb2[9].z
if_nz r0.y
  dp3 r0.y, r11.xyzx, r11.xyzx
  rsq r1.z, r0.y
  mul r3.xyz, r1.zzzz, r11.xyzx
  sqrt r0.y, r0.y
  lt r1.z, l(0.000000), cb2[13].w
  if_nz r1.z
    mad r1.zw, r0.yyyy, cb2[15].xxxy, cb2[14].zzzw
    mul r1.zw, r1.zzzw, cb2[16].xxxy
    lt r3.w, l(0.010000), |r11.z|
    mul r4.xy, r11.zzzz, cb2[15].zwzz
    mul r4.zw, r4.xxxy, l(0.000000, 0.000000, -1.442695, -1.442695)
    exp r4.zw, r4.zzzw
    add r4.zw, -r4.zzzw, l(0.000000, 0.000000, 1.000000, 1.000000)
    div r4.xy, r4.zwzz, r4.xyxx
    mul r4.xy, r1.zwzz, r4.xyxx
    movc r1.zw, r3.wwww, r4.xxxy, r1.zzzw
    mul r4.xyz, r1.zzzz, cb2[12].xyzx
    exp r4.xyz, r4.xyzx
    mul r5.xyw, r1.wwww, cb2[12].xyxz
    exp r5.xyw, r5.xyxw
    add r5.xyw, -r4.xyxz, r5.xyxw
    mad r4.xyz, cb2[13].wwww, r5.xywx, r4.xyzx
  else 
    mad r1.z, r0.y, cb2[15].x, cb2[14].z
    mul r1.z, r1.z, cb2[16].x
    lt r1.w, l(0.010000), |r11.z|
    mul r3.w, r11.z, cb2[15].z
    mul r4.w, r3.w, l(-1.442695)
    exp r4.w, r4.w
    add r4.w, -r4.w, l(1.000000)
    div r3.w, r4.w, r3.w
    mul r3.w, r1.z, r3.w
    movc r1.z, r1.w, r3.w, r1.z
    mul r5.xyw, r1.zzzz, cb2[12].xyxz
    exp r4.xyz, r5.xywx
  endif 
  mad r4.xyz, r4.xyzx, cb2[9].zzzz, l(1.000000, 1.000000, 1.000000, 0.000000)
  add_sat r4.xyz, r4.xyzx, -cb2[9].zzzz
  dp3 r1.z, cb2[7].yzwy, -r3.xyzx
  mad r1.w, -cb2[8].w, cb2[8].w, l(1.000000)
  mad r3.x, cb2[8].w, -r1.z, l(1.000000)
  mul r3.x, r3.x, r3.x
  mul r3.x, r3.x, l(12.566371)
  div r1.w, r1.w, r3.x
  add r0.y, r0.y, -cb2[10].w
  mul_sat r0.y, r0.y, cb2[11].w
  mul r0.y, r0.y, r1.w
  mov_sat r1.z, r1.z
  mad r1.z, r1.z, r1.z, l(1.000000)
  mad r1.z, r1.z, l(0.05968310), l(-1.000000)
  mad r1.z, cb2[8].z, r1.z, l(1.000000)
  mul r3.xyz, r0.yyyy, cb2[11].xyzx
  mad r3.xyz, r1.zzzz, cb2[10].xyzx, r3.xyzx
  mul r3.xyz, r3.xyzx, cb2[9].wwww
  add r5.xyw, -r4.xyxz, l(1.000000, 1.000000, 0.000000, 1.000000)
  mul r3.xyz, r3.xyzx, r5.xywx
  mad r3.xyz, r2.xywx, r4.xyzx, r3.xyzx
else 
  mul r0.y, r11.z, cb2[6].x
  mad r1.z, cb2[6].x, r11.z, cb2[5].x
  lt r1.w, |r0.y|, l(0.000100)
  min r3.w, r1.z, l(64.000000)
  mul r3.w, r3.w, l(1.442695)
  exp r3.w, r3.w
  mov_sat r4.x, cb2[6].z
  lt r4.y, r1.z, l(0.000000)
  add r1.z, r1.z, l(1.000000)
  movc r1.z, r4.y, r3.w, r1.z
  add r1.z, r1.z, -cb2[6].z
  movc r0.y, r1.w, l(1.000000), r0.y
  div r0.y, r1.z, r0.y
  movc r0.y, r1.w, r4.x, r0.y
  mul r0.y, r0.y, cb2[5].z
  dp3 r1.z, r11.xyzx, r11.xyzx
  sqrt r1.w, r1.z
  mad r0.y, r0.y, r1.w, cb2[5].w
  exp r0.y, r0.y
  min r0.y, r0.y, l(1.000000)
  add r0.y, -r0.y, l(1.000000)
  rsq r1.z, r1.z
  mul r4.xyz, r1.zzzz, r11.xyzx
  dp3 r1.z, cb2[7].yzwy, r4.xyzx
  mad_sat r1.z, cb2[8].y, r1.z, cb2[8].x
  add r4.xyzw, cb2[3].xyzw, -cb2[4].xyzw
  mad r4.xyzw, r1.zzzz, r4.xyzw, cb2[4].xyzw
  mul r0.y, r0.y, r4.w
  add r4.xyz, -r2.xywx, r4.xyzx
  mad r3.xyz, r0.yyyy, r4.xyzx, r2.xywx
endif 
mul r2.xyw, r3.xyxz, cb1[85].yyyy
ge r3.xyz, r2.xywx, l(0.00006104, 0.00006104, 0.00006104, 0.000000)
and r2.xyw, r2.xyxw, r3.xyxz
min r2.xyw, r2.xyxw, l(65024.000000, 65024.000000, 0.000000, 64512.000000)
ilt r0.y, l(0), cb2[55].w
and r3.xyzw, cb2[55].wwww, l(32, 3, 64, 12)
ine r1.zw, r3.xxxz, l(0, 0, 0, 0)
ieq r3.xy, r3.ywyy, l(3, 12, 0, 0)
and r1.zw, r1.zzzw, r3.xxxy
and r3.xy, r1.zwzz, l(0x3e4ccccd, 0x3e4ccccd, 0, 0)
and r1.z, cb2[55].w, l(16)
ine r1.w, r1.z, l(0)
ieq r1.z, r1.z, l(16)
and r1.z, r1.z, r1.w
and r3.z, r1.z, l(0x3e4ccccd)
mad r3.xyz, r3.xyzx, cb1[85].xxxx, -r2.xywx
mad r3.xyz, r3.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000), r2.xywx
movc r2.xyw, r0.yyyy, r3.xyxz, r2.xyxw
if_nz cb2[52].y
  if_nz cb2[53].y
    switch cb2[53].y
      case l(1)
      and r0.y, r5.z, l(3)
      break 
      case l(2)
      ubfe r0.y, l(2), l(8), r5.z
      break 
      case l(3)
      ushr r0.y, r5.z, l(16)
      break 
      case l(4)
      and r0.y, r0.x, l(15)
      break 
      case l(5)
      ushr r0.y, r0.x, l(8)
      break 
      default 
      mov r0.y, l(0)
      break 
    endswitch 
    utof r0.y, r0.y
    mul r0.y, r0.y, cb2[53].z
    mad r3.xyz, r0.yyyy, l(0.500000, 0.500000, 0.500000, 0.000000), -r2.xywx
    mad r2.xyw, cb2[53].wwww, r3.xyxz, r2.xyxw
  endif 
endif 
store_uav_typed u0.xyzw, r1.xyyy, r2.xywx
if_nz r2.z
  add r1.xyz, r11.xyzx, cb1[24].xyzx
  and r1.w, r5.z, l(3)
  store_structured u2.xyzw, cb2[52].x, l(92), r1.xyzw
  and r0.y, r0.x, l(15)
  store_structured u2.x, cb2[52].x, l(108), r0.y
endif 
if_nz cb2[52].y
  and r0.y, r5.z, l(3)
  atomic_iadd g1, l(0), r0.y
  ubfe r1.x, l(2), l(8), r5.z
  atomic_iadd g1, l(4), r1.x
  ushr r1.y, r5.z, l(16)
  atomic_iadd g1, l(8), r1.y
  and r1.z, r0.x, l(15)
  atomic_iadd g1, l(12), r1.z
  ushr r0.x, r0.x, l(8)
  atomic_iadd g1, l(16), r0.x
  atomic_umax g2, l(0), r0.y
  atomic_umax g2, l(4), r1.x
  atomic_umax g2, l(8), r1.y
  atomic_umax g2, l(12), r1.z
  atomic_umax g2, l(16), r0.x
  imm_atomic_iadd r1.x, g0, l(0), l(1)
  ieq r0.x, r1.x, l(63)
  if_nz r0.x
    ld_raw r1.xyzw, l(0), g1.xyzw
    mov r2.xz, cb2[52].xxxx
    mov r2.yw, l(0,40,0,44)
    atomic_iadd u2, r2.xyxx, r1.x
    atomic_iadd u2, r2.zwzz, r1.y
    mov r2.xz, cb2[52].xxxx
    mov r2.yw, l(0,48,0,52)
    atomic_iadd u2, r2.xyxx, r1.z
    atomic_iadd u2, r2.zwzz, r1.w
    ld_raw r0.x, l(16), g1.xxxx
    mov r1.xz, cb2[52].xxxx
    mov r1.yw, l(0,56,0,0)
    atomic_iadd u2, r1.xyxx, r0.x
    ld_raw r2.xyzw, l(0), g2.xyzw
    atomic_umax u2, r1.zwzz, r2.x
    mov r1.xz, cb2[52].xxxx
    mov r1.yw, l(0,4,0,8)
    atomic_umax u2, r1.xyxx, r2.y
    atomic_umax u2, r1.zwzz, r2.z
    mov r1.xz, cb2[52].xxxx
    mov r1.yw, l(0,12,0,16)
    atomic_umax u2, r1.xyxx, r2.w
    ld_raw r0.x, l(16), g2.xxxx
    atomic_umax u2, r1.zwzz, r0.x
    ieq r0.yz, r0.zzwz, cb2[52].zzwz
    and r0.y, r0.z, r0.y
    if_nz r0.y
      store_structured u2.xyzw, cb2[52].x, l(20), r2.xyzw
      store_structured u2.x, cb2[52].x, l(36), r0.x
    endif 
  endif 
endif 
ret 
// Approximately 1652 instruction slots used
