//
// Generated by Microsoft (R) HLSL Shader Compiler 9.30.9200.16384
//
//   using 3Dmigoto v1.2.45 on Thu Jul 15 15:24:22 2021
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// bilinearClamp                     sampler      NA          NA             s0      1 
// codeTexture0                      texture  float4          2d             t0      1 
// codeTexture1                      texture  float4          2d             t1      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// TEXCOORD                 0   xy          0     NONE   float   xy  
// SV_POSITION              0   xyzw        1      POS   float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyz         0   TARGET   float   xyz 
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_sampler s0, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_resource_texture2d (float,float,float,float) t1
dcl_input_ps linear v0.xy
dcl_output o0.xyz
dcl_temps 2
gather4_indexable(texture2d)(float,float,float,float) r0.xyzw, v0.xyxx, t1.xyzw, s0.x
mul_sat r0.xyzw, r0.xyzw, l(340282346638528859811704183484516925440.000000, 340282346638528859811704183484516925440.000000, 340282346638528859811704183484516925440.000000, 340282346638528859811704183484516925440.000000)
add r1.x, r0.y, r0.x
add r1.x, r0.z, r1.x
add r1.x, r0.w, r1.x
lt r1.y, l(0.000000), r1.x
rcp r1.x, r1.x
and r1.x, r1.x, r1.y
mul r0.xyzw, r0.xyzw, r1.xxxx
gather4_indexable(texture2d)(float,float,float,float) r1.xyzw, v0.xyxx, t0.xyzw, s0.x
dp4 o0.x, r1.xyzw, r0.xyzw
gather4_indexable(texture2d)(float,float,float,float) r1.xyzw, v0.xyxx, t0.xyzw, s0.y
dp4 o0.y, r1.xyzw, r0.xyzw
gather4_indexable(texture2d)(float,float,float,float) r1.xyzw, v0.xyxx, t0.xyzw, s0.z
dp4 o0.z, r1.xyzw, r0.xyzw
ret 
// Approximately 16 instruction slots used
