//
// Generated by Microsoft (R) HLSL Shader Compiler 9.30.9200.16384
//
//   using 3Dmigoto v1.2.45 on Thu Jul 15 15:24:18 2021
//
//
// Buffer Definitions: 
//
// cbuffer PerSceneConsts
// {
//
//   row_major float4x4 projectionMatrix;// Offset:    0 Size:    64 [unused]
//   row_major float4x4 viewMatrix;     // Offset:   64 Size:    64
//   row_major float4x4 viewProjectionMatrix;// Offset:  128 Size:    64 [unused]
//   row_major float4x4 inverseProjectionMatrix;// Offset:  192 Size:    64
//   row_major float4x4 inverseViewMatrix;// Offset:  256 Size:    64
//   row_major float4x4 inverseViewProjectionMatrix;// Offset:  320 Size:    64 [unused]
//   float4 eyeOffset;                  // Offset:  384 Size:    16 [unused]
//   float4 adsZScale;                  // Offset:  400 Size:    16 [unused]
//   float4 hdrControl0;                // Offset:  416 Size:    16 [unused]
//   float4 hdrControl1;                // Offset:  432 Size:    16 [unused]
//   float4 fogColor;                   // Offset:  448 Size:    16 [unused]
//   float4 fogConsts;                  // Offset:  464 Size:    16 [unused]
//   float4 fogConsts2;                 // Offset:  480 Size:    16 [unused]
//   float4 fogConsts3;                 // Offset:  496 Size:    16 [unused]
//   float4 fogConsts4;                 // Offset:  512 Size:    16 [unused]
//   float4 fogConsts5;                 // Offset:  528 Size:    16 [unused]
//   float4 fogConsts6;                 // Offset:  544 Size:    16 [unused]
//   float4 fogConsts7;                 // Offset:  560 Size:    16 [unused]
//   float4 fogConsts8;                 // Offset:  576 Size:    16 [unused]
//   float4 fogConsts9;                 // Offset:  592 Size:    16 [unused]
//   float3 sunFogDir;                  // Offset:  608 Size:    12 [unused]
//   float4 sunFogColor;                // Offset:  624 Size:    16 [unused]
//   float2 sunFog;                     // Offset:  640 Size:     8 [unused]
//   float4 zNear;                      // Offset:  656 Size:    16 [unused]
//   float3 clothPrimaryTint;           // Offset:  672 Size:    12 [unused]
//   float3 clothSecondaryTint;         // Offset:  688 Size:    12 [unused]
//   float4 renderTargetSize;           // Offset:  704 Size:    16
//   float4 upscaledTargetSize;         // Offset:  720 Size:    16 [unused]
//   float4 materialColor;              // Offset:  736 Size:    16 [unused]
//   float4 cameraUp;                   // Offset:  752 Size:    16 [unused]
//   float4 cameraLook;                 // Offset:  768 Size:    16 [unused]
//   float4 cameraSide;                 // Offset:  784 Size:    16 [unused]
//   float4 cameraVelocity;             // Offset:  800 Size:    16 [unused]
//   float4 skyMxR;                     // Offset:  816 Size:    16 [unused]
//   float4 skyMxG;                     // Offset:  832 Size:    16 [unused]
//   float4 skyMxB;                     // Offset:  848 Size:    16 [unused]
//   float4 sunMxR;                     // Offset:  864 Size:    16 [unused]
//   float4 sunMxG;                     // Offset:  880 Size:    16 [unused]
//   float4 sunMxB;                     // Offset:  896 Size:    16 [unused]
//   float4 skyRotationTransition;      // Offset:  912 Size:    16 [unused]
//   float4 debugColorOverride;         // Offset:  928 Size:    16 [unused]
//   float4 debugAlphaOverride;         // Offset:  944 Size:    16 [unused]
//   float4 debugNormalOverride;        // Offset:  960 Size:    16 [unused]
//   float4 debugSpecularOverride;      // Offset:  976 Size:    16 [unused]
//   float4 debugGlossOverride;         // Offset:  992 Size:    16 [unused]
//   float4 debugOcclusionOverride;     // Offset: 1008 Size:    16 [unused]
//   float4 debugStreamerControl;       // Offset: 1024 Size:    16 [unused]
//   float4 emblemLUTSelector;          // Offset: 1040 Size:    16 [unused]
//   float4 colorMatrixR;               // Offset: 1056 Size:    16 [unused]
//   float4 colorMatrixG;               // Offset: 1072 Size:    16 [unused]
//   float4 colorMatrixB;               // Offset: 1088 Size:    16 [unused]
//   float4 gameTime;                   // Offset: 1104 Size:    16 [unused]
//   float4 gameTick;                   // Offset: 1120 Size:    16 [unused]
//   float4 subpixelOffset;             // Offset: 1136 Size:    16
//   float4 viewportDimensions;         // Offset: 1152 Size:    16 [unused]
//   float4 viewSpaceScaleBias;         // Offset: 1168 Size:    16 [unused]
//   float4 ui3dUVSetup0;               // Offset: 1184 Size:    16 [unused]
//   float4 ui3dUVSetup1;               // Offset: 1200 Size:    16 [unused]
//   float4 ui3dUVSetup2;               // Offset: 1216 Size:    16 [unused]
//   float4 ui3dUVSetup3;               // Offset: 1232 Size:    16 [unused]
//   float4 ui3dUVSetup4;               // Offset: 1248 Size:    16 [unused]
//   float4 ui3dUVSetup5;               // Offset: 1264 Size:    16 [unused]
//   float4 clipSpaceLookupScale;       // Offset: 1280 Size:    16 [unused]
//   float4 clipSpaceLookupOffset;      // Offset: 1296 Size:    16 [unused]
//   uint4 computeSpriteControl;        // Offset: 1312 Size:    16 [unused]
//   float4 invBcTexSizes;              // Offset: 1328 Size:    16 [unused]
//   float4 invMaskTexSizes;            // Offset: 1344 Size:    16 [unused]
//   float4 relHDRExposure;             // Offset: 1360 Size:    16 [unused]
//   uint4 triDensityFlags;             // Offset: 1376 Size:    16 [unused]
//   float4 triDensityParams;           // Offset: 1392 Size:    16 [unused]
//   float4 voldecalRevealTextureInfo;  // Offset: 1408 Size:    16 [unused]
//   float4 extraClipPlane0;            // Offset: 1424 Size:    16 [unused]
//   float4 extraClipPlane1;            // Offset: 1440 Size:    16 [unused]
//   float4 shaderDebug;                // Offset: 1456 Size:    16 [unused]
//   uint isDepthHack;                  // Offset: 1472 Size:     4 [unused]
//
// }
//
// cbuffer LightingGlobals
// {
//
//   uint numLights;                    // Offset:    0 Size:     4
//   uint numRefProbes;                 // Offset:    4 Size:     4
//   uint numRefProbeBlends;            // Offset:    8 Size:     4 [unused]
//   uint numDedicatedLights;           // Offset:   12 Size:     4 [unused]
//   float4 clearColor;                 // Offset:   16 Size:    16 [unused]
//   float4 sssParams;                  // Offset:   32 Size:    16 [unused]
//   
//   struct CoreFogConstants
//   {
//       
//       float4 fogColor;               // Offset:   48
//       float4 sunFogColor;            // Offset:   64
//       float K0;                      // Offset:   80
//       float skyK0;                   // Offset:   84
//       float expMul;                  // Offset:   88
//       float expAdd;                  // Offset:   92
//       float heightFalloff;           // Offset:   96
//       float skyHeightFalloff;        // Offset:  100
//       float K0b;                     // Offset:  104
//       float padding0;                // Offset:  108
//       float skyK0b;                  // Offset:  112
//       float3 wldSunFogDir;           // Offset:  116
//       float2 sunFogAngles;           // Offset:  128
//       float atmospheresunstrength;   // Offset:  136
//       float atmosphereMieSchlickK;   // Offset:  140
//       float2 atmosphereskyfogdensityatcamera;// Offset:  144
//       float atmosphereExtinctionIntensity;// Offset:  152
//       float atmosphereInScatterIntensity;// Offset:  156
//       float3 atmosphereRayleighDensity;// Offset:  160
//       float atmospherehazebasedist;  // Offset:  172
//       float3 atmosphereMieDensity;   // Offset:  176
//       float atmospherehazefadedist;  // Offset:  188
//       float3 atmosphereTotalDensity; // Offset:  192
//       float worldfogskysize;         // Offset:  204
//       float3 atmosphereInScatterIntensityOverTotalDensity;// Offset:  208
//       float blendAmount;             // Offset:  220
//       float2 atmosphereskyfogheightdensityscale;// Offset:  224
//       float2 atmospherefogdistanceoffset;// Offset:  232
//       float2 atmospherefogdistancedensityscale;// Offset:  240
//       float2 atmospherefogheightdensityscale;// Offset:  248
//       float2 atmospherefogdensityatcamera;// Offset:  256
//       float2 padding1;               // Offset:  264
//
//   } fogConstants;                    // Offset:   48 Size:   224 [unused]
//   
//   struct CoreSunConstants
//   {
//       
//       float3 wldDir;                 // Offset:  272
//       float splitDepthOffset;        // Offset:  284
//       float3 color;                  // Offset:  288
//       float specScale;               // Offset:  300
//       float globalProbeExposure;     // Offset:  304
//       float3 avgGlobalProbeColor;    // Offset:  308
//       float4 splitPinTransform[3];   // Offset:  320
//       uint sunCookieIndex;           // Offset:  368
//       float sunCookieIntensity;      // Offset:  372
//       float sunVolumetricCookieIntensity;// Offset:  376
//       uint toolsGfxDisableSunShadow; // Offset:  380
//       float4 sunCookieTransform[2];  // Offset:  384
//       float intensity;               // Offset:  416
//       int splitArrayOffset;          // Offset:  420
//       float2 pad0;                   // Offset:  424
//       
//       struct SSTLightingConstants
//       {
//           
//           struct SSTConstants
//           {
//               
//               float2 dimensionInTiles;// Offset:  432
//               float inchesPerTexel;  // Offset:  440
//               float spanInInches;    // Offset:  444
//
//           } constants;               // Offset:  432
//           row_major float4x4 offToPinTransform;// Offset:  448
//           float coordScale;          // Offset:  512
//           uint rootOffset;           // Offset:  516
//           uint2 pad0;                // Offset:  520
//
//       } sstLightingConstants;        // Offset:  432
//
//   } sunConstants;                    // Offset:  272 Size:   256 [unused]
//   
//   struct SSTMinMaxConstants
//   {
//       
//       float2 sstToMinMaxScale;       // Offset:  528
//       float2 pad0;                   // Offset:  536
//       float2 halfMinTexelSize;       // Offset:  544
//       float rcpInchesDimLevel0;      // Offset:  552
//       float shadowBiasInches;        // Offset:  556
//
//   } minMaxConstants;                 // Offset:  528 Size:    32 [unused]
//   
//   struct CoreGlobalProbePack
//   {
//       
//       uint4 data[3];                 // Offset:  560
//
//   } globalProbeConstants;            // Offset:  560 Size:    48 [unused]
//   
//   struct CoreWeatherConsts
//   {
//       
//       float rain;                    // Offset:  608
//       float windSpeed;               // Offset:  612
//       float windDirSin;              // Offset:  616
//       float windDirCos;              // Offset:  620
//       float weatherTile;             // Offset:  624
//       float3 weatherVector;          // Offset:  628
//       float3 weatherVector2;         // Offset:  640
//       float padding0;                // Offset:  652
//       float3 weatherTint;            // Offset:  656
//       float padding1;                // Offset:  668
//       float3 weatherTint2;           // Offset:  672
//       float padding2;                // Offset:  684
//
//   } weather;                         // Offset:  608 Size:    80 [unused]
//   
//   struct SSTLightingConstants
//   {
//       
//       struct SSTConstants
//       {
//           
//           float2 dimensionInTiles;   // Offset:  688
//           float inchesPerTexel;      // Offset:  696
//           float spanInInches;        // Offset:  700
//
//       } constants;                   // Offset:  688
//       row_major float4x4 offToPinTransform;// Offset:  704
//       float coordScale;              // Offset:  768
//       uint rootOffset;               // Offset:  772
//       uint2 pad0;                    // Offset:  776
//
//   } outdoorSSTConstants;             // Offset:  688 Size:    96 [unused]
//   float4 pinToWorldZ;                // Offset:  784 Size:    16 [unused]
//   
//   struct CoreVolumetricConstants
//   {
//       
//       uint firstSpotLight;           // Offset:  800
//       uint lastSpotLight;            // Offset:  804
//       uint firstOmniLight;           // Offset:  808
//       uint lastOmniLight;            // Offset:  812
//       uint firstProbe;               // Offset:  816
//       uint lastProbe;                // Offset:  820
//       uint padding0;                 // Offset:  824
//       uint padding1;                 // Offset:  828
//
//   } volumetric;                      // Offset:  800 Size:    32 [unused]
//   uint viewID;                       // Offset:  832 Size:     4 [unused]
//   uint enableCountDebug;             // Offset:  836 Size:     4 [unused]
//   uint centerGroupIDx;               // Offset:  840 Size:     4 [unused]
//   uint centerGroupIDy;               // Offset:  844 Size:     4 [unused]
//   uint viewmodelSunShadowRaw;        // Offset:  848 Size:     4 [unused]
//   uint debugDrawOverlayType;         // Offset:  852 Size:     4 [unused]
//   float drawNumLighstScale;          // Offset:  856 Size:     4 [unused]
//   float drawNumLightsAlpha;          // Offset:  860 Size:     4 [unused]
//   uint probeDebug;                   // Offset:  864 Size:     4 [unused]
//   float probeDebugRadius;            // Offset:  868 Size:     4 [unused]
//   uint showSunVis;                   // Offset:  872 Size:     4 [unused]
//   uint enableAO;                     // Offset:  876 Size:     4 [unused]
//   uint showAO;                       // Offset:  880 Size:     4 [unused]
//   uint numGpuCullTilesWidth;         // Offset:  884 Size:     4 [unused]
//   uint numGpuCullTilesHeight;        // Offset:  888 Size:     4 [unused]
//   int permuteHighlight;              // Offset:  892 Size:     4 [unused]
//   uint overdrawOverlayMaxValue;      // Offset:  896 Size:     4 [unused]
//   float overdrawOverlayAlpha;        // Offset:  900 Size:     4 [unused]
//   uint overdrawDecals;               // Offset:  904 Size:     4 [unused]
//   uint overdrawDecalsLayers;         // Offset:  908 Size:     4 [unused]
//   uint permuteStride;                // Offset:  912 Size:     4
//   uint numDecals;                    // Offset:  916 Size:     4 [unused]
//   uint numStaticDecals;              // Offset:  920 Size:     4 [unused]
//   uint numDynamicDecals;             // Offset:  924 Size:     4 [unused]
//   uint numOverrideProbes;            // Offset:  928 Size:     4 [unused]
//   uint enableDitheredShadow;         // Offset:  932 Size:     4 [unused]
//   uint oitMaxEntries;                // Offset:  936 Size:     4 [unused]
//   uint numAttenuationVolumes;        // Offset:  940 Size:     4 [unused]
//
// }
//
// Resource bind info for gCullConstants
// {
//
//   struct CoreCullConstantsPack
//   {
//       
//       uint4 data[5];                 // Offset:    0
//
//   } $Element;                        // Offset:    0 Size:    80
//
// }
//
// Resource bind info for gPermuteExtentsBuffer
// {
//
//   struct GpuTileDepthExtents
//   {
//       
//       float min;                     // Offset:    0
//       float max;                     // Offset:    4
//
//   } $Element;                        // Offset:    0 Size:     8
//
// }
//
// Resource bind info for gPermutedTilingBuffer
// {
//
//   struct PermutedTilingBuffer
//   {
//       
//       uint2 data;                    // Offset:    0
//
//   } $Element;                        // Offset:    0 Size:     8
//
// }
//
// Resource bind info for gPermuteAccumulateBuffer
// {
//
//   uint $Element;                     // Offset:    0 Size:     4
//
// }
//
// Resource bind info for gDeferredCullBits
// {
//
//   uint $Element;                     // Offset:    0 Size:     4
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// gCullConstants                    texture  struct         r/o            t11      1 
// gPermuteExtentsBuffer             texture  struct         r/o            t24      1 
// gPermutedTilingBuffer                 UAV  struct         r/w             u5      1 
// gPermuteAccumulateBuffer              UAV  struct         r/w             u6      1 
// gDeferredCullBits                     UAV  struct         r/w             u7      1 
// PerSceneConsts                    cbuffer      NA          NA            cb1      1 
// LightingGlobals                   cbuffer      NA          NA            cb2      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_immediateConstantBuffer { { 1.000000, 0, 0, 0},
                              { 0, 1.000000, 0, 0},
                              { 0, 0, 1.000000, 0},
                              { 0, 0, 0, 1.000000} }
dcl_constantbuffer CB1[72], immediateIndexed
dcl_constantbuffer CB2[58], immediateIndexed
dcl_resource_structured t11, 80
dcl_resource_structured t24, 8
dcl_uav_structured u5, 8
dcl_uav_structured u6, 4
dcl_uav_structured u7, 4
dcl_input vThreadGroupID.x
dcl_input vThreadIDInGroup.x
dcl_temps 36
dcl_thread_group 64, 1, 1
add r0.xy, cb1[44].xyxx, l(7.000000, 7.000000, 0.000000, 0.000000)
ftou r0.xy, r0.xyxx
ushr r0.xy, r0.xyxx, l(3, 3, 0, 0)
imad r0.z, vThreadGroupID.x, l(64), vThreadIDInGroup.x
imul null, r0.y, r0.y, r0.x
uge r0.y, r0.z, r0.y
if_nz r0.y
  ret 
endif 
ld_structured_indexable(structured_buffer, stride=8)(mixed,mixed,mixed,mixed) r0.yw, r0.z, l(0), t24.xxxy
eq r1.x, r0.y, l(340282346638528859811704183484516925440.000000)
if_nz r1.x
  ret 
endif 
lt r1.x, r0.w, l(0.000000)
udiv r0.x, r2.x, r0.z, r0.x
mov r2.y, r0.x
ishl r1.yz, r2.xxyx, l(0, 3, 3, 0)
ishl r0.z, vThreadIDInGroup.x, l(5)
imad r0.z, vThreadGroupID.x, l(2048), r0.z
utof r3.xyw, r1.yzyz
add r2.yz, r3.xxyx, l(0.000000, 0.500000, 0.500000, 0.000000)
add r2.yz, r2.yyzy, -cb1[71].xxyx
mul r2.yz, r2.yyzy, cb1[44].zzwz
mad r2.yz, r2.yyzy, l(0.000000, 2.000000, -2.000000, 0.000000), l(0.000000, -1.000000, 1.000000, 0.000000)
mov r3.x, cb1[12].x
mov r3.y, cb1[13].y
mul r4.xy, r2.yzyy, r3.xyxx
mov r4.z, l(1.000000)
mul r2.yzw, |r0.yyyy|, r4.xxyz
mul r5.xyz, r2.zzzz, cb1[17].xyzx
mad r5.xyz, r2.yyyy, cb1[16].xyzx, r5.xyzx
mad r2.yzw, r2.wwww, cb1[18].xxyz, r5.xxyz
iadd r1.zw, r1.yyyz, l(0, 0, 8, 8)
utof r3.z, r1.z
add r3.zw, r3.zzzw, -cb1[71].xxxy
add r3.zw, r3.zzzw, l(0.000000, 0.000000, 0.500000, 0.500000)
mul r3.zw, r3.zzzw, cb1[44].zzzw
mad r3.zw, r3.zzzw, l(0.000000, 0.000000, 2.000000, -2.000000), l(0.000000, 0.000000, -1.000000, 1.000000)
mul r5.xy, r3.xyxx, r3.zwzz
mov r5.z, l(1.000000)
mul r6.xyz, |r0.yyyy|, r5.xyzx
mul r7.xyz, r6.yyyy, cb1[17].xyzx
mad r6.xyw, r6.xxxx, cb1[16].xyxz, r7.xyxz
mad r6.xyz, r6.zzzz, cb1[18].xyzx, r6.xywx
utof r7.xyzw, r1.zwyw
add r1.zw, r7.xxxy, -cb1[71].xxxy
add r1.zw, r1.zzzw, l(0.000000, 0.000000, 0.500000, 0.500000)
mul r1.zw, r1.zzzw, cb1[44].zzzw
mad r1.zw, r1.zzzw, l(0.000000, 0.000000, 2.000000, -2.000000), l(0.000000, 0.000000, -1.000000, 1.000000)
mul r8.xy, r3.xyxx, r1.zwzz
mov r8.z, l(1.000000)
mul r9.xyz, |r0.yyyy|, r8.xyzx
mul r10.xyz, r9.yyyy, cb1[17].yzxy
mad r9.xyw, r9.xxxx, cb1[16].yzyx, r10.xyxz
mad r9.xyz, r9.zzzz, cb1[18].yzxy, r9.xywx
add r1.yz, r7.zzwz, -cb1[71].xxyx
add r1.yz, r1.yyzy, l(0.000000, 0.500000, 0.500000, 0.000000)
mul r1.yz, r1.yyzy, cb1[44].zzwz
mad r1.yz, r1.yyzy, l(0.000000, 2.000000, -2.000000, 0.000000), l(0.000000, -1.000000, 1.000000, 0.000000)
mul r3.xy, r3.xyxx, r1.yzyy
mov r3.z, l(1.000000)
mul r1.yzw, |r0.yyyy|, r3.xxyz
mul r7.xyz, r1.zzzz, cb1[17].xyzx
mad r7.xyz, r1.yyyy, cb1[16].xyzx, r7.xyzx
mad r1.yzw, r1.wwww, cb1[18].xxyz, r7.xxyz
mul r4.xyz, |r0.wwww|, r4.xyzx
mul r7.xyz, r4.yyyy, cb1[17].yzxy
mad r4.xyw, r4.xxxx, cb1[16].yzyx, r7.xyxz
mad r4.xyz, r4.zzzz, cb1[18].yzxy, r4.xywx
mul r5.xyz, |r0.wwww|, r5.xyzx
mul r7.xyz, r5.yyyy, cb1[17].zxyz
mad r5.xyw, r5.xxxx, cb1[16].zxzy, r7.xyxz
mad r5.xyz, r5.zzzz, cb1[18].zxyz, r5.xywx
mul r7.xyz, |r0.wwww|, r8.xyzx
mul r8.xyz, r7.yyyy, cb1[17].xyzx
mad r7.xyw, r7.xxxx, cb1[16].xyxz, r8.xyxz
mad r7.xyz, r7.zzzz, cb1[18].xyzx, r7.xywx
mul r3.xyz, |r0.wwww|, r3.xyzx
mul r8.xyz, r3.yyyy, cb1[17].zxyz
mad r3.xyw, r3.xxxx, cb1[16].zxzy, r8.xyxz
mad r3.xyz, r3.zzzz, cb1[18].zxyz, r3.xywx
mul r8.xyz, r6.xyzx, l(0.125000, 0.125000, 0.125000, 0.000000)
mad r8.xyz, r2.yzwy, l(0.125000, 0.125000, 0.125000, 0.000000), r8.xyzx
mad r8.xyz, r9.zxyz, l(0.125000, 0.125000, 0.125000, 0.000000), r8.xyzx
mad r8.xyz, r1.yzwy, l(0.125000, 0.125000, 0.125000, 0.000000), r8.xyzx
mad r8.xyz, r4.zxyz, l(0.125000, 0.125000, 0.125000, 0.000000), r8.xyzx
mad r8.xyz, r5.yzxy, l(0.125000, 0.125000, 0.125000, 0.000000), r8.xyzx
mad r8.xyz, r7.xyzx, l(0.125000, 0.125000, 0.125000, 0.000000), r8.xyzx
mad r8.xyz, r3.yzxy, l(0.125000, 0.125000, 0.125000, 0.000000), r8.xyzx
add r10.xyz, r2.yzwy, -r8.xyzx
add r11.xyz, r6.xyzx, -r8.xyzx
max r10.xyz, |r10.xyzx|, |r11.xyzx|
add r11.xyz, -r8.xyzx, r9.zxyz
max r10.xyz, r10.xyzx, |r11.xyzx|
add r11.xyz, r1.yzwy, -r8.xyzx
max r10.xyz, r10.xyzx, |r11.xyzx|
add r11.xyz, r4.zxyz, -r8.xyzx
max r10.xyz, r10.xyzx, |r11.xyzx|
add r11.xyz, r5.yzxy, -r8.xyzx
max r10.xyz, r10.xyzx, |r11.xyzx|
add r11.xyz, r7.xyzx, -r8.xyzx
max r10.xyz, r10.xyzx, |r11.xyzx|
add r11.xyz, r3.yzxy, -r8.xyzx
max r10.xyz, r10.xyzx, |r11.xyzx|
if_nz cb2[0].y
  movc r0.y, r1.x, l(48), l(16)
  iadd r0.w, cb2[0].y, cb2[0].x
  add r11.xyz, r2.yzwy, r9.zxyz
  mad r11.xyz, r11.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000), -cb1[7].xyzx
  add r12.xyz, r4.zxyz, r7.xyzx
  mad r12.xyz, r12.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000), -cb1[7].xyzx
  add r13.xyz, r6.xyzx, r9.zxyz
  mad r13.xyz, -r13.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000), r11.xyzx
  add r14.xyz, r2.yzwy, r6.xyzx
  mad r14.xyz, -r14.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000), r11.xyzx
  add r15.xyz, r5.yzxy, r7.xyzx
  mad r15.xyz, -r15.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000), r12.xyzx
  add r16.xyz, r4.zxyz, r5.yzxy
  mad r16.xyz, -r16.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000), r12.xyzx
  iadd r3.w, r0.z, l(16)
  add r17.xyz, r12.yzxy, -r15.yzxy
  add r18.xyz, -r16.yzxy, r17.xyzx
  add r19.xyz, r11.yzxy, -r13.yzxy
  add r20.xyz, -r14.yzxy, r19.xyzx
  add r18.xyz, r18.xyzx, -r20.xyzx
  add r20.xyz, r12.yzxy, r15.yzxy
  add r21.xyz, r16.yzxy, r20.xyzx
  add r22.xyz, r11.yzxy, r13.yzxy
  add r23.xyz, r14.yzxy, r22.xyzx
  add r21.xyz, r21.xyzx, -r23.xyzx
  mul r23.xyz, r18.xyzx, cb1[4].zxyz
  mad r23.xyz, cb1[4].yzxy, r18.yzxy, -r23.xyzx
  mul r24.xyz, r21.xyzx, cb1[4].zxyz
  mad r24.xyz, cb1[4].yzxy, r21.yzxy, -r24.xyzx
  mul r25.xyz, r18.xyzx, cb1[5].zxyz
  mad r25.xyz, cb1[5].yzxy, r18.yzxy, -r25.xyzx
  mul r26.xyz, r21.xyzx, cb1[5].zxyz
  mad r26.xyz, cb1[5].yzxy, r21.yzxy, -r26.xyzx
  dp3 r4.w, r11.xyzx, cb1[6].xyzx
  dp3 r5.w, r13.xyzx, cb1[6].xyzx
  dp3 r6.w, r14.xyzx, cb1[6].xyzx
  add r5.w, |r5.w|, |r6.w|
  dp3 r6.w, r12.xyzx, cb1[6].xyzx
  dp3 r7.w, r15.xyzx, cb1[6].xyzx
  dp3 r8.w, r16.xyzx, cb1[6].xyzx
  add r7.w, |r7.w|, |r8.w|
  add r8.w, r4.w, -r5.w
  add r9.w, r6.w, -r7.w
  min r8.w, r8.w, r9.w
  add r4.w, r4.w, r5.w
  add r5.w, r6.w, r7.w
  max r4.w, r4.w, r5.w
  dp3 r5.w, r11.xyzx, r24.xyzx
  dp3 r6.w, r11.xyzx, r23.xyzx
  dp3 r7.w, r13.xyzx, r23.xyzx
  dp3 r9.w, r14.xyzx, r23.xyzx
  add r7.w, |r7.w|, |r9.w|
  dp3 r9.w, r12.xyzx, r23.xyzx
  dp3 r10.w, r15.xyzx, r23.xyzx
  dp3 r11.w, r16.xyzx, r23.xyzx
  add r10.w, |r10.w|, |r11.w|
  add r11.w, r6.w, -r7.w
  add r12.w, r9.w, -r10.w
  min r11.w, r11.w, r12.w
  add r6.w, r6.w, r7.w
  add r7.w, r9.w, r10.w
  max r6.w, r6.w, r7.w
  dp3 r7.w, r13.xyzx, r24.xyzx
  dp3 r9.w, r14.xyzx, r24.xyzx
  add r7.w, |r7.w|, |r9.w|
  dp3 r9.w, r12.xyzx, r24.xyzx
  dp3 r10.w, r15.xyzx, r24.xyzx
  dp3 r12.w, r16.xyzx, r24.xyzx
  add r10.w, |r10.w|, |r12.w|
  add r12.w, r5.w, -r7.w
  add r13.w, r9.w, -r10.w
  min r12.w, r12.w, r13.w
  add r5.w, r5.w, r7.w
  add r7.w, r9.w, r10.w
  max r5.w, r5.w, r7.w
  dp3 r7.w, r11.xyzx, r25.xyzx
  dp3 r9.w, r13.xyzx, r25.xyzx
  dp3 r10.w, r14.xyzx, r25.xyzx
  add r9.w, |r9.w|, |r10.w|
  dp3 r10.w, r12.xyzx, r25.xyzx
  dp3 r13.w, r15.xyzx, r25.xyzx
  dp3 r14.w, r16.xyzx, r25.xyzx
  add r13.w, |r13.w|, |r14.w|
  add r14.w, r7.w, -r9.w
  add r15.w, r10.w, -r13.w
  min r14.w, r14.w, r15.w
  add r7.w, r7.w, r9.w
  add r9.w, r10.w, r13.w
  max r7.w, r7.w, r9.w
  dp3 r9.w, r11.xyzx, r26.xyzx
  dp3 r10.w, r13.xyzx, r26.xyzx
  dp3 r13.w, r14.xyzx, r26.xyzx
  add r10.w, |r10.w|, |r13.w|
  dp3 r13.w, r12.xyzx, r26.xyzx
  dp3 r15.w, r15.xyzx, r26.xyzx
  dp3 r16.w, r16.xyzx, r26.xyzx
  add r15.w, |r15.w|, |r16.w|
  add r16.w, r9.w, -r10.w
  add r17.w, r13.w, -r15.w
  min r16.w, r16.w, r17.w
  add r9.w, r9.w, r10.w
  add r10.w, r13.w, r15.w
  max r9.w, r9.w, r10.w
  add r20.xyz, -r16.yzxy, r20.xyzx
  add r22.xyz, -r14.yzxy, r22.xyzx
  add r20.xyz, r20.xyzx, -r22.xyzx
  add r17.xyz, r16.yzxy, r17.xyzx
  add r19.xyz, r14.yzxy, r19.xyzx
  add r17.xyz, r17.xyzx, -r19.xyzx
  mov r19.y, l(0)
  mov r10.w, r3.w
  mov r22.xyzw, l(0,0,0,0)
  mov r13.w, cb2[0].x
  loop 
    uge r15.w, r13.w, r0.w
    breakc_nz r15.w
    iadd r15.w, r13.w, -cb2[0].x
    and r17.w, r15.w, l(31)
    ld_structured_indexable(structured_buffer, stride=80)(mixed,mixed,mixed,mixed) r27.xyzw, r13.w, l(0), t11.xyzw
    ld_structured_indexable(structured_buffer, stride=80)(mixed,mixed,mixed,mixed) r28.xyzw, r13.w, l(16), t11.xyzw
    add r29.xyz, -r8.xyzx, r27.xyzx
    mov r30.x, r27.w
    mov r30.yz, r28.xxyx
    add r30.xyz, r10.xyzx, r30.xyzx
    lt r29.xyz, r30.xyzx, |r29.xyzx|
    or r18.w, r29.y, r29.x
    or r18.w, r29.z, r18.w
    if_z r18.w
      ld_structured_indexable(structured_buffer, stride=80)(mixed,mixed,mixed,mixed) r29.xyzw, r13.w, l(32), t11.xyzw
      ld_structured_indexable(structured_buffer, stride=80)(mixed,mixed,mixed,mixed) r30.xyzw, r13.w, l(48), t11.xyzw
      ld_structured_indexable(structured_buffer, stride=80)(mixed,mixed,mixed,mixed) r31.xy, r13.w, l(64), t11.xyxx
      mul r28.xyz, r28.zzzz, r29.yzwy
      mul r32.xyz, r28.wwww, r30.xyzx
      mov r31.z, r30.w
      mul r33.xyz, r29.xxxx, r31.zxyz
      mov r19.zw, l(0,0,0,0)
      mov r18.w, l(0)
      loop 
        ige r20.w, r19.w, l(3)
        mov r18.w, l(0)
        breakc_nz r20.w
        mul r34.xyz, r29.yzwy, icb[r19.w + 0].xxxx
        mad r34.xyz, icb[r19.w + 0].yyyy, r30.xyzx, r34.xyzx
        mad r34.xyz, icb[r19.w + 0].zzzz, r31.zxyz, r34.xyzx
        dp3 r20.w, r27.xyzx, r34.xyzx
        dp3 r21.w, r28.xyzx, r34.xyzx
        dp3 r23.w, r32.xyzx, r34.xyzx
        add r21.w, |r21.w|, |r23.w|
        dp3 r23.w, r33.xyzx, r34.xyzx
        add r21.w, r21.w, |r23.w|
        add r23.w, r20.w, -r21.w
        add r20.w, r20.w, r21.w
        dp3 r21.w, r11.xyzx, r34.xyzx
        dp3 r24.w, r13.xyzx, r34.xyzx
        dp3 r25.w, r14.xyzx, r34.xyzx
        add r24.w, |r24.w|, |r25.w|
        dp3 r25.w, r12.xyzx, r34.xyzx
        dp3 r26.w, r15.xyzx, r34.xyzx
        dp3 r27.w, r16.xyzx, r34.xyzx
        add r26.w, |r26.w|, |r27.w|
        add r27.w, r21.w, -r24.w
        add r28.w, r25.w, -r26.w
        min r27.w, r27.w, r28.w
        add r21.w, r21.w, r24.w
        add r24.w, r25.w, r26.w
        max r21.w, r21.w, r24.w
        lt r20.w, r20.w, r27.w
        lt r21.w, r21.w, r23.w
        or r20.w, r20.w, r21.w
        if_nz r20.w
          mov r19.z, l(-1)
          mov r18.w, l(-1)
          break 
        endif 
        iadd r19.x, r19.w, l(1)
        mov r19.zw, r19.yyyx
        mov r18.w, r20.w
      endloop 
      if_z r18.w
        dp3 r19.x, r27.xyzx, cb1[6].xyzx
        dp3 r19.w, r28.xyzx, cb1[6].xyzx
        dp3 r20.w, r32.xyzx, cb1[6].xyzx
        add r19.w, |r19.w|, |r20.w|
        dp3 r20.w, r33.xyzx, cb1[6].xyzx
        add r19.w, r19.w, |r20.w|
        add r20.w, -r19.w, r19.x
        add r19.x, r19.w, r19.x
        lt r19.x, r19.x, r8.w
        lt r19.w, r4.w, r20.w
        or r19.x, r19.w, r19.x
        or r19.z, r19.z, r19.x
        not r19.w, r19.x
        if_z r19.x
          if_z r19.x
            dp3 r20.w, r27.xyzx, r23.xyzx
            dp3 r21.w, r28.xyzx, r23.xyzx
            dp3 r23.w, r32.xyzx, r23.xyzx
            add r21.w, |r21.w|, |r23.w|
            dp3 r23.w, r33.xyzx, r23.xyzx
            add r21.w, r21.w, |r23.w|
            add r23.w, r20.w, -r21.w
            add r20.w, r20.w, r21.w
            lt r20.w, r20.w, r11.w
            lt r21.w, r6.w, r23.w
            or r34.y, r20.w, r21.w
            or r19.z, r19.z, r34.y
            mov r34.x, r34.y
          else 
            mov r34.xy, l(-1,-1,0,0)
          endif 
          and r34.xy, r19.wwww, r34.yxyy
          or r19.xw, r19.xxxx, r34.yyyx
        else 
          mov r19.xw, l(-1,0,0,-1)
        endif 
        not r19.w, r19.w
        not r20.w, r19.x
        and r19.w, r19.w, r20.w
        if_nz r19.w
          dp3 r19.w, r27.xyzx, r24.xyzx
          dp3 r20.w, r28.xyzx, r24.xyzx
          dp3 r21.w, r32.xyzx, r24.xyzx
          add r20.w, |r20.w|, |r21.w|
          dp3 r21.w, r33.xyzx, r24.xyzx
          add r20.w, r20.w, |r21.w|
          add r21.w, r19.w, -r20.w
          add r19.w, r19.w, r20.w
          lt r19.w, r19.w, r12.w
          lt r20.w, r5.w, r21.w
          or r19.w, r19.w, r20.w
          or r19.z, r19.z, r19.w
          mov r19.xz, r19.wwzw
        else 
          mov r19.w, l(-1)
        endif 
        not r19.w, r19.w
        not r20.w, r19.x
        and r19.w, r19.w, r20.w
        if_nz r19.w
          dp3 r19.w, r27.xyzx, r25.xyzx
          dp3 r20.w, r28.xyzx, r25.xyzx
          dp3 r21.w, r32.xyzx, r25.xyzx
          add r20.w, |r20.w|, |r21.w|
          dp3 r21.w, r33.xyzx, r25.xyzx
          add r20.w, r20.w, |r21.w|
          add r21.w, r19.w, -r20.w
          add r19.w, r19.w, r20.w
          lt r19.w, r19.w, r14.w
          lt r20.w, r7.w, r21.w
          or r19.w, r19.w, r20.w
          or r19.z, r19.z, r19.w
          mov r19.xz, r19.wwzw
        else 
          mov r19.w, l(-1)
        endif 
        not r19.w, r19.w
        not r20.w, r19.x
        and r19.w, r19.w, r20.w
        if_nz r19.w
          dp3 r19.w, r27.xyzx, r26.xyzx
          dp3 r20.w, r28.xyzx, r26.xyzx
          dp3 r21.w, r32.xyzx, r26.xyzx
          add r20.w, |r20.w|, |r21.w|
          dp3 r21.w, r33.xyzx, r26.xyzx
          add r20.w, r20.w, |r21.w|
          add r21.w, r19.w, -r20.w
          add r19.w, r19.w, r20.w
          lt r19.w, r19.w, r16.w
          lt r20.w, r9.w, r21.w
          or r19.x, r19.w, r20.w
          or r19.z, r19.z, r19.x
        endif 
        if_z r19.x
          mul r34.xyz, r29.wyzw, cb1[4].yzxy
          mad r34.xyz, r29.zwyz, cb1[4].zxyz, -r34.xyzx
          dp3 r19.x, r27.xyzx, r34.xyzx
          dp3 r19.w, r28.xyzx, r34.xyzx
          dp3 r20.w, r32.xyzx, r34.xyzx
          add r19.w, |r19.w|, |r20.w|
          dp3 r20.w, r33.xyzx, r34.xyzx
          add r19.w, r19.w, |r20.w|
          add r20.w, -r19.w, r19.x
          add r19.x, r19.w, r19.x
          dp3 r19.w, r11.xyzx, r34.xyzx
          dp3 r21.w, r13.xyzx, r34.xyzx
          dp3 r23.w, r14.xyzx, r34.xyzx
          add r21.w, |r21.w|, |r23.w|
          dp3 r23.w, r12.xyzx, r34.xyzx
          dp3 r24.w, r15.xyzx, r34.xyzx
          dp3 r25.w, r16.xyzx, r34.xyzx
          add r24.w, |r24.w|, |r25.w|
          add r25.w, r19.w, -r21.w
          add r26.w, r23.w, -r24.w
          min r25.w, r25.w, r26.w
          add r19.w, r19.w, r21.w
          add r21.w, r23.w, r24.w
          max r19.w, r19.w, r21.w
          lt r19.x, r19.x, r25.w
          lt r19.w, r19.w, r20.w
          or r19.x, r19.w, r19.x
          or r19.w, r19.z, r19.x
          not r20.w, r19.x
          if_z r19.x
            if_z r19.x
              mul r34.xyz, r30.zxyz, cb1[4].yzxy
              mad r34.xyz, r30.yzxy, cb1[4].zxyz, -r34.xyzx
              dp3 r21.w, r27.xyzx, r34.xyzx
              dp3 r23.w, r28.xyzx, r34.xyzx
              dp3 r24.w, r32.xyzx, r34.xyzx
              add r23.w, |r23.w|, |r24.w|
              dp3 r24.w, r33.xyzx, r34.xyzx
              add r23.w, r23.w, |r24.w|
              add r24.w, r21.w, -r23.w
              add r21.w, r21.w, r23.w
              dp3 r23.w, r11.xyzx, r34.xyzx
              dp3 r25.w, r13.xyzx, r34.xyzx
              dp3 r26.w, r14.xyzx, r34.xyzx
              add r25.w, |r25.w|, |r26.w|
              dp3 r26.w, r12.xyzx, r34.xyzx
              dp3 r27.w, r15.xyzx, r34.xyzx
              dp3 r28.w, r16.xyzx, r34.xyzx
              add r27.w, |r27.w|, |r28.w|
              add r28.w, r23.w, -r25.w
              add r29.x, r26.w, -r27.w
              min r28.w, r28.w, r29.x
              add r23.w, r23.w, r25.w
              add r25.w, r26.w, r27.w
              max r23.w, r23.w, r25.w
              lt r21.w, r21.w, r28.w
              lt r23.w, r23.w, r24.w
              or r34.y, r21.w, r23.w
              or r19.w, r19.w, r34.y
              mov r34.x, r34.y
            else 
              mov r34.xy, l(-1,-1,0,0)
            endif 
            and r34.xy, r20.wwww, r34.yxyy
            or r34.xy, r19.xxxx, r34.yxyy
          else 
            mov r34.xy, l(-1,-1,0,0)
          endif 
          not r19.x, r34.y
          not r20.w, r34.x
          and r19.x, r19.x, r20.w
          if_nz r19.x
            mul r34.yzw, r31.yyzx, cb1[4].yyzx
            mad r34.yzw, r31.xxyz, cb1[4].zzxy, -r34.yyzw
            dp3 r19.x, r27.xyzx, r34.yzwy
            dp3 r20.w, r28.xyzx, r34.yzwy
            dp3 r21.w, r32.xyzx, r34.yzwy
            add r20.w, |r20.w|, |r21.w|
            dp3 r21.w, r33.xyzx, r34.yzwy
            add r20.w, r20.w, |r21.w|
            add r21.w, r19.x, -r20.w
            add r19.x, r19.x, r20.w
            dp3 r20.w, r11.xyzx, r34.yzwy
            dp3 r23.w, r13.xyzx, r34.yzwy
            dp3 r24.w, r14.xyzx, r34.yzwy
            add r23.w, |r23.w|, |r24.w|
            dp3 r24.w, r12.xyzx, r34.yzwy
            dp3 r25.w, r15.xyzx, r34.yzwy
            dp3 r26.w, r16.xyzx, r34.yzwy
            add r25.w, |r25.w|, |r26.w|
            add r26.w, r20.w, -r23.w
            add r27.w, r24.w, -r25.w
            min r26.w, r26.w, r27.w
            add r20.w, r20.w, r23.w
            add r23.w, r24.w, r25.w
            max r20.w, r20.w, r23.w
            lt r19.x, r19.x, r26.w
            lt r20.w, r20.w, r21.w
            or r34.x, r19.x, r20.w
            or r19.w, r19.w, r34.x
          endif 
          not r19.x, r34.x
          if_z r34.x
            if_z r34.x
              if_z r34.x
                mul r34.xyz, r29.wyzw, cb1[5].yzxy
                mad r34.xyz, r29.zwyz, cb1[5].zxyz, -r34.xyzx
                dp3 r20.w, r27.xyzx, r34.xyzx
                dp3 r21.w, r28.xyzx, r34.xyzx
                dp3 r23.w, r32.xyzx, r34.xyzx
                add r21.w, |r21.w|, |r23.w|
                dp3 r23.w, r33.xyzx, r34.xyzx
                add r21.w, r21.w, |r23.w|
                add r23.w, r20.w, -r21.w
                add r20.w, r20.w, r21.w
                dp3 r21.w, r11.xyzx, r34.xyzx
                dp3 r24.w, r13.xyzx, r34.xyzx
                dp3 r25.w, r14.xyzx, r34.xyzx
                add r24.w, |r24.w|, |r25.w|
                dp3 r25.w, r12.xyzx, r34.xyzx
                dp3 r26.w, r15.xyzx, r34.xyzx
                dp3 r27.w, r16.xyzx, r34.xyzx
                add r26.w, |r26.w|, |r27.w|
                add r27.w, r21.w, -r24.w
                add r28.w, r25.w, -r26.w
                min r27.w, r27.w, r28.w
                add r21.w, r21.w, r24.w
                add r24.w, r25.w, r26.w
                max r21.w, r21.w, r24.w
                lt r20.w, r20.w, r27.w
                lt r21.w, r21.w, r23.w
                or r20.w, r20.w, r21.w
                or r19.w, r19.w, r20.w
                mov r34.x, r20.w
              else 
                mov r34.x, l(-1)
                mov r20.w, l(0)
              endif 
            else 
              mov r34.x, l(-1)
              mov r20.w, l(-1)
            endif 
            not r20.w, r20.w
            not r21.w, r34.x
            and r20.w, r20.w, r21.w
            if_nz r20.w
              mul r35.xyz, r30.zxyz, cb1[5].yzxy
              mad r35.xyz, r30.yzxy, cb1[5].zxyz, -r35.xyzx
              dp3 r20.w, r27.xyzx, r35.xyzx
              dp3 r21.w, r28.xyzx, r35.xyzx
              dp3 r23.w, r32.xyzx, r35.xyzx
              add r21.w, |r21.w|, |r23.w|
              dp3 r23.w, r33.xyzx, r35.xyzx
              add r21.w, r21.w, |r23.w|
              add r23.w, r20.w, -r21.w
              add r20.w, r20.w, r21.w
              dp3 r21.w, r11.xyzx, r35.xyzx
              dp3 r24.w, r13.xyzx, r35.xyzx
              dp3 r25.w, r14.xyzx, r35.xyzx
              add r24.w, |r24.w|, |r25.w|
              dp3 r25.w, r12.xyzx, r35.xyzx
              dp3 r26.w, r15.xyzx, r35.xyzx
              dp3 r27.w, r16.xyzx, r35.xyzx
              add r26.w, |r26.w|, |r27.w|
              add r27.w, r21.w, -r24.w
              add r28.w, r25.w, -r26.w
              min r27.w, r27.w, r28.w
              add r21.w, r21.w, r24.w
              add r24.w, r25.w, r26.w
              max r21.w, r21.w, r24.w
              lt r20.w, r20.w, r27.w
              lt r21.w, r21.w, r23.w
              or r20.w, r20.w, r21.w
              or r19.w, r19.w, r20.w
              mov r34.x, r20.w
            else 
              mov r20.w, l(-1)
            endif 
            not r20.w, r20.w
            not r21.w, r34.x
            and r20.w, r20.w, r21.w
            if_nz r20.w
              mul r35.xyz, r31.yzxy, cb1[5].yzxy
              mad r35.xyz, r31.xyzx, cb1[5].zxyz, -r35.xyzx
              dp3 r20.w, r27.xyzx, r35.xyzx
              dp3 r21.w, r28.xyzx, r35.xyzx
              dp3 r23.w, r32.xyzx, r35.xyzx
              add r21.w, |r21.w|, |r23.w|
              dp3 r23.w, r33.xyzx, r35.xyzx
              add r21.w, r21.w, |r23.w|
              add r23.w, r20.w, -r21.w
              add r20.w, r20.w, r21.w
              dp3 r21.w, r11.xyzx, r35.xyzx
              dp3 r24.w, r13.xyzx, r35.xyzx
              dp3 r25.w, r14.xyzx, r35.xyzx
              add r24.w, |r24.w|, |r25.w|
              dp3 r25.w, r12.xyzx, r35.xyzx
              dp3 r26.w, r15.xyzx, r35.xyzx
              dp3 r27.w, r16.xyzx, r35.xyzx
              add r26.w, |r26.w|, |r27.w|
              add r27.w, r21.w, -r24.w
              add r28.w, r25.w, -r26.w
              min r27.w, r27.w, r28.w
              add r21.w, r21.w, r24.w
              add r24.w, r25.w, r26.w
              max r21.w, r21.w, r24.w
              lt r20.w, r20.w, r27.w
              lt r21.w, r21.w, r23.w
              or r34.x, r20.w, r21.w
              or r19.w, r19.w, r34.x
            endif 
          else 
            mov r34.x, l(-1)
          endif 
          not r20.w, r34.x
          and r19.x, r19.x, r20.w
          if_nz r19.x
            mul r35.xyz, r18.xyzx, r29.wyzw
            mad r35.xyz, r29.zwyz, r18.yzxy, -r35.xyzx
            dp3 r20.w, r27.xyzx, r35.xyzx
            dp3 r21.w, r28.xyzx, r35.xyzx
            dp3 r23.w, r32.xyzx, r35.xyzx
            add r21.w, |r21.w|, |r23.w|
            dp3 r23.w, r33.xyzx, r35.xyzx
            add r21.w, r21.w, |r23.w|
            add r23.w, r20.w, -r21.w
            add r20.w, r20.w, r21.w
            dp3 r21.w, r11.xyzx, r35.xyzx
            dp3 r24.w, r13.xyzx, r35.xyzx
            dp3 r25.w, r14.xyzx, r35.xyzx
            add r24.w, |r24.w|, |r25.w|
            dp3 r25.w, r12.xyzx, r35.xyzx
            dp3 r26.w, r15.xyzx, r35.xyzx
            dp3 r27.w, r16.xyzx, r35.xyzx
            add r26.w, |r26.w|, |r27.w|
            add r27.w, r21.w, -r24.w
            add r28.w, r25.w, -r26.w
            min r27.w, r27.w, r28.w
            add r21.w, r21.w, r24.w
            add r24.w, r25.w, r26.w
            max r21.w, r21.w, r24.w
            lt r20.w, r20.w, r27.w
            lt r21.w, r21.w, r23.w
            or r20.w, r20.w, r21.w
            or r19.w, r19.w, r20.w
            not r21.w, r20.w
            if_z r20.w
              if_z r20.w
                mul r35.xyz, r18.xyzx, r30.zxyz
                mad r35.xyz, r30.yzxy, r18.yzxy, -r35.xyzx
                dp3 r23.w, r27.xyzx, r35.xyzx
                dp3 r24.w, r28.xyzx, r35.xyzx
                dp3 r25.w, r32.xyzx, r35.xyzx
                add r24.w, |r24.w|, |r25.w|
                dp3 r25.w, r33.xyzx, r35.xyzx
                add r24.w, r24.w, |r25.w|
                add r25.w, r23.w, -r24.w
                add r23.w, r23.w, r24.w
                dp3 r24.w, r11.xyzx, r35.xyzx
                dp3 r26.w, r13.xyzx, r35.xyzx
                dp3 r27.w, r14.xyzx, r35.xyzx
                add r26.w, |r26.w|, |r27.w|
                dp3 r27.w, r12.xyzx, r35.xyzx
                dp3 r28.w, r15.xyzx, r35.xyzx
                dp3 r29.x, r16.xyzx, r35.xyzx
                add r28.w, |r28.w|, |r29.x|
                add r29.x, r24.w, -r26.w
                add r30.w, r27.w, -r28.w
                min r29.x, r29.x, r30.w
                add r24.w, r24.w, r26.w
                add r26.w, r27.w, r28.w
                max r24.w, r24.w, r26.w
                lt r23.w, r23.w, r29.x
                lt r24.w, r24.w, r25.w
                or r35.y, r23.w, r24.w
                or r19.w, r19.w, r35.y
                mov r35.x, r35.y
              else 
                mov r35.xy, l(-1,-1,0,0)
              endif 
              and r34.zw, r21.wwww, r35.yyyx
              or r34.xy, r20.wwww, r34.wzww
            else 
              mov r34.xy, l(-1,-1,0,0)
            endif 
            not r20.w, r34.y
            not r21.w, r34.x
            and r20.w, r20.w, r21.w
            if_nz r20.w
              mul r35.xyz, r18.xyzx, r31.yzxy
              mad r35.xyz, r31.xyzx, r18.yzxy, -r35.xyzx
              dp3 r20.w, r27.xyzx, r35.xyzx
              dp3 r21.w, r28.xyzx, r35.xyzx
              dp3 r23.w, r32.xyzx, r35.xyzx
              add r21.w, |r21.w|, |r23.w|
              dp3 r23.w, r33.xyzx, r35.xyzx
              add r21.w, r21.w, |r23.w|
              add r23.w, r20.w, -r21.w
              add r20.w, r20.w, r21.w
              dp3 r21.w, r11.xyzx, r35.xyzx
              dp3 r24.w, r13.xyzx, r35.xyzx
              dp3 r25.w, r14.xyzx, r35.xyzx
              add r24.w, |r24.w|, |r25.w|
              dp3 r25.w, r12.xyzx, r35.xyzx
              dp3 r26.w, r15.xyzx, r35.xyzx
              dp3 r27.w, r16.xyzx, r35.xyzx
              add r26.w, |r26.w|, |r27.w|
              add r27.w, r21.w, -r24.w
              add r28.w, r25.w, -r26.w
              min r27.w, r27.w, r28.w
              add r21.w, r21.w, r24.w
              add r24.w, r25.w, r26.w
              max r21.w, r21.w, r24.w
              lt r20.w, r20.w, r27.w
              lt r21.w, r21.w, r23.w
              or r34.x, r20.w, r21.w
              or r19.w, r19.w, r34.x
            endif 
          endif 
          not r20.w, r34.x
          and r19.x, r19.x, r20.w
          if_nz r19.x
            mul r35.xyz, r20.xyzx, r29.wyzw
            mad r35.xyz, r29.zwyz, r20.yzxy, -r35.xyzx
            dp3 r20.w, r27.xyzx, r35.xyzx
            dp3 r21.w, r28.xyzx, r35.xyzx
            dp3 r23.w, r32.xyzx, r35.xyzx
            add r21.w, |r21.w|, |r23.w|
            dp3 r23.w, r33.xyzx, r35.xyzx
            add r21.w, r21.w, |r23.w|
            add r23.w, r20.w, -r21.w
            add r20.w, r20.w, r21.w
            dp3 r21.w, r11.xyzx, r35.xyzx
            dp3 r24.w, r13.xyzx, r35.xyzx
            dp3 r25.w, r14.xyzx, r35.xyzx
            add r24.w, |r24.w|, |r25.w|
            dp3 r25.w, r12.xyzx, r35.xyzx
            dp3 r26.w, r15.xyzx, r35.xyzx
            dp3 r27.w, r16.xyzx, r35.xyzx
            add r26.w, |r26.w|, |r27.w|
            add r27.w, r21.w, -r24.w
            add r28.w, r25.w, -r26.w
            min r27.w, r27.w, r28.w
            add r21.w, r21.w, r24.w
            add r24.w, r25.w, r26.w
            max r21.w, r21.w, r24.w
            lt r20.w, r20.w, r27.w
            lt r21.w, r21.w, r23.w
            or r20.w, r20.w, r21.w
            or r19.w, r19.w, r20.w
            not r21.w, r20.w
            if_z r20.w
              if_z r20.w
                mul r35.xyz, r20.xyzx, r30.zxyz
                mad r35.xyz, r30.yzxy, r20.yzxy, -r35.xyzx
                dp3 r23.w, r27.xyzx, r35.xyzx
                dp3 r24.w, r28.xyzx, r35.xyzx
                dp3 r25.w, r32.xyzx, r35.xyzx
                add r24.w, |r24.w|, |r25.w|
                dp3 r25.w, r33.xyzx, r35.xyzx
                add r24.w, r24.w, |r25.w|
                add r25.w, r23.w, -r24.w
                add r23.w, r23.w, r24.w
                dp3 r24.w, r11.xyzx, r35.xyzx
                dp3 r26.w, r13.xyzx, r35.xyzx
                dp3 r27.w, r14.xyzx, r35.xyzx
                add r26.w, |r26.w|, |r27.w|
                dp3 r27.w, r12.xyzx, r35.xyzx
                dp3 r28.w, r15.xyzx, r35.xyzx
                dp3 r29.x, r16.xyzx, r35.xyzx
                add r28.w, |r28.w|, |r29.x|
                add r29.x, r24.w, -r26.w
                add r30.w, r27.w, -r28.w
                min r29.x, r29.x, r30.w
                add r24.w, r24.w, r26.w
                add r26.w, r27.w, r28.w
                max r24.w, r24.w, r26.w
                lt r23.w, r23.w, r29.x
                lt r24.w, r24.w, r25.w
                or r35.y, r23.w, r24.w
                or r19.w, r19.w, r35.y
                mov r35.x, r35.y
              else 
                mov r35.xy, l(-1,-1,0,0)
              endif 
              and r34.zw, r21.wwww, r35.yyyx
              or r34.xy, r20.wwww, r34.wzww
            else 
              mov r34.xy, l(-1,-1,0,0)
            endif 
            not r20.w, r34.y
            not r21.w, r34.x
            and r20.w, r20.w, r21.w
            if_nz r20.w
              mul r35.xyz, r20.xyzx, r31.yzxy
              mad r35.xyz, r31.xyzx, r20.yzxy, -r35.xyzx
              dp3 r20.w, r27.xyzx, r35.xyzx
              dp3 r21.w, r28.xyzx, r35.xyzx
              dp3 r23.w, r32.xyzx, r35.xyzx
              add r21.w, |r21.w|, |r23.w|
              dp3 r23.w, r33.xyzx, r35.xyzx
              add r21.w, r21.w, |r23.w|
              add r23.w, r20.w, -r21.w
              add r20.w, r20.w, r21.w
              dp3 r21.w, r11.xyzx, r35.xyzx
              dp3 r24.w, r13.xyzx, r35.xyzx
              dp3 r25.w, r14.xyzx, r35.xyzx
              add r24.w, |r24.w|, |r25.w|
              dp3 r25.w, r12.xyzx, r35.xyzx
              dp3 r26.w, r15.xyzx, r35.xyzx
              dp3 r27.w, r16.xyzx, r35.xyzx
              add r26.w, |r26.w|, |r27.w|
              add r27.w, r21.w, -r24.w
              add r28.w, r25.w, -r26.w
              min r27.w, r27.w, r28.w
              add r21.w, r21.w, r24.w
              add r24.w, r25.w, r26.w
              max r21.w, r21.w, r24.w
              lt r20.w, r20.w, r27.w
              lt r21.w, r21.w, r23.w
              or r34.x, r20.w, r21.w
              or r19.w, r19.w, r34.x
            endif 
          endif 
          not r20.w, r34.x
          and r19.x, r19.x, r20.w
          if_nz r19.x
            mul r35.xyz, r17.xyzx, r29.wyzw
            mad r35.xyz, r29.zwyz, r17.yzxy, -r35.xyzx
            dp3 r20.w, r27.xyzx, r35.xyzx
            dp3 r21.w, r28.xyzx, r35.xyzx
            dp3 r23.w, r32.xyzx, r35.xyzx
            add r21.w, |r21.w|, |r23.w|
            dp3 r23.w, r33.xyzx, r35.xyzx
            add r21.w, r21.w, |r23.w|
            add r23.w, r20.w, -r21.w
            add r20.w, r20.w, r21.w
            dp3 r21.w, r11.xyzx, r35.xyzx
            dp3 r24.w, r13.xyzx, r35.xyzx
            dp3 r25.w, r14.xyzx, r35.xyzx
            add r24.w, |r24.w|, |r25.w|
            dp3 r25.w, r12.xyzx, r35.xyzx
            dp3 r26.w, r15.xyzx, r35.xyzx
            dp3 r27.w, r16.xyzx, r35.xyzx
            add r26.w, |r26.w|, |r27.w|
            add r27.w, r21.w, -r24.w
            add r28.w, r25.w, -r26.w
            min r27.w, r27.w, r28.w
            add r21.w, r21.w, r24.w
            add r24.w, r25.w, r26.w
            max r21.w, r21.w, r24.w
            lt r20.w, r20.w, r27.w
            lt r21.w, r21.w, r23.w
            or r20.w, r20.w, r21.w
            or r19.w, r19.w, r20.w
            not r21.w, r20.w
            if_z r20.w
              if_z r20.w
                mul r35.xyz, r17.xyzx, r30.zxyz
                mad r35.xyz, r30.yzxy, r17.yzxy, -r35.xyzx
                dp3 r23.w, r27.xyzx, r35.xyzx
                dp3 r24.w, r28.xyzx, r35.xyzx
                dp3 r25.w, r32.xyzx, r35.xyzx
                add r24.w, |r24.w|, |r25.w|
                dp3 r25.w, r33.xyzx, r35.xyzx
                add r24.w, r24.w, |r25.w|
                add r25.w, r23.w, -r24.w
                add r23.w, r23.w, r24.w
                dp3 r24.w, r11.xyzx, r35.xyzx
                dp3 r26.w, r13.xyzx, r35.xyzx
                dp3 r27.w, r14.xyzx, r35.xyzx
                add r26.w, |r26.w|, |r27.w|
                dp3 r27.w, r12.xyzx, r35.xyzx
                dp3 r28.w, r15.xyzx, r35.xyzx
                dp3 r29.x, r16.xyzx, r35.xyzx
                add r28.w, |r28.w|, |r29.x|
                add r29.x, r24.w, -r26.w
                add r30.w, r27.w, -r28.w
                min r29.x, r29.x, r30.w
                add r24.w, r24.w, r26.w
                add r26.w, r27.w, r28.w
                max r24.w, r24.w, r26.w
                lt r23.w, r23.w, r29.x
                lt r24.w, r24.w, r25.w
                or r35.y, r23.w, r24.w
                or r19.w, r19.w, r35.y
                mov r35.x, r35.y
              else 
                mov r35.xy, l(-1,-1,0,0)
              endif 
              and r34.zw, r21.wwww, r35.yyyx
              or r34.xy, r20.wwww, r34.wzww
            else 
              mov r34.xy, l(-1,-1,0,0)
            endif 
            not r20.w, r34.y
            not r21.w, r34.x
            and r20.w, r20.w, r21.w
            if_nz r20.w
              mul r35.xyz, r17.xyzx, r31.yzxy
              mad r35.xyz, r31.xyzx, r17.yzxy, -r35.xyzx
              dp3 r20.w, r27.xyzx, r35.xyzx
              dp3 r21.w, r28.xyzx, r35.xyzx
              dp3 r23.w, r32.xyzx, r35.xyzx
              add r21.w, |r21.w|, |r23.w|
              dp3 r23.w, r33.xyzx, r35.xyzx
              add r21.w, r21.w, |r23.w|
              add r23.w, r20.w, -r21.w
              add r20.w, r20.w, r21.w
              dp3 r21.w, r11.xyzx, r35.xyzx
              dp3 r24.w, r13.xyzx, r35.xyzx
              dp3 r25.w, r14.xyzx, r35.xyzx
              add r24.w, |r24.w|, |r25.w|
              dp3 r25.w, r12.xyzx, r35.xyzx
              dp3 r26.w, r15.xyzx, r35.xyzx
              dp3 r27.w, r16.xyzx, r35.xyzx
              add r26.w, |r26.w|, |r27.w|
              add r27.w, r21.w, -r24.w
              add r28.w, r25.w, -r26.w
              min r27.w, r27.w, r28.w
              add r21.w, r21.w, r24.w
              add r24.w, r25.w, r26.w
              max r21.w, r21.w, r24.w
              lt r20.w, r20.w, r27.w
              lt r21.w, r21.w, r23.w
              or r34.x, r20.w, r21.w
              or r19.w, r19.w, r34.x
            endif 
          endif 
          not r20.w, r34.x
          and r19.x, r19.x, r20.w
          if_nz r19.x
            mul r35.xyz, r21.xyzx, r29.wyzw
            mad r29.xyz, r29.zwyz, r21.yzxy, -r35.xyzx
            dp3 r19.x, r27.xyzx, r29.xyzx
            dp3 r20.w, r28.xyzx, r29.xyzx
            dp3 r21.w, r32.xyzx, r29.xyzx
            add r20.w, |r20.w|, |r21.w|
            dp3 r21.w, r33.xyzx, r29.xyzx
            add r20.w, r20.w, |r21.w|
            add r21.w, r19.x, -r20.w
            add r19.x, r19.x, r20.w
            dp3 r20.w, r11.xyzx, r29.xyzx
            dp3 r23.w, r13.xyzx, r29.xyzx
            dp3 r24.w, r14.xyzx, r29.xyzx
            add r23.w, |r23.w|, |r24.w|
            dp3 r24.w, r12.xyzx, r29.xyzx
            dp3 r25.w, r15.xyzx, r29.xyzx
            dp3 r26.w, r16.xyzx, r29.xyzx
            add r25.w, |r25.w|, |r26.w|
            add r26.w, r20.w, -r23.w
            add r27.w, r24.w, -r25.w
            min r26.w, r26.w, r27.w
            add r20.w, r20.w, r23.w
            add r23.w, r24.w, r25.w
            max r20.w, r20.w, r23.w
            lt r19.x, r19.x, r26.w
            lt r20.w, r20.w, r21.w
            or r19.x, r19.x, r20.w
            or r19.w, r19.w, r19.x
            not r20.w, r19.x
            if_z r19.x
              if_z r19.x
                mul r29.xyz, r21.xyzx, r30.zxyz
                mad r29.xyz, r30.yzxy, r21.yzxy, -r29.xyzx
                dp3 r21.w, r27.xyzx, r29.xyzx
                dp3 r23.w, r28.xyzx, r29.xyzx
                dp3 r24.w, r32.xyzx, r29.xyzx
                add r23.w, |r23.w|, |r24.w|
                dp3 r24.w, r33.xyzx, r29.xyzx
                add r23.w, r23.w, |r24.w|
                add r24.w, r21.w, -r23.w
                add r21.w, r21.w, r23.w
                dp3 r23.w, r11.xyzx, r29.xyzx
                dp3 r25.w, r13.xyzx, r29.xyzx
                dp3 r26.w, r14.xyzx, r29.xyzx
                add r25.w, |r25.w|, |r26.w|
                dp3 r26.w, r12.xyzx, r29.xyzx
                dp3 r27.w, r15.xyzx, r29.xyzx
                dp3 r28.w, r16.xyzx, r29.xyzx
                add r27.w, |r27.w|, |r28.w|
                add r28.w, r23.w, -r25.w
                add r29.x, r26.w, -r27.w
                min r28.w, r28.w, r29.x
                add r23.w, r23.w, r25.w
                add r25.w, r26.w, r27.w
                max r23.w, r23.w, r25.w
                lt r21.w, r21.w, r28.w
                lt r23.w, r23.w, r24.w
                or r29.y, r21.w, r23.w
                or r19.w, r19.w, r29.y
                mov r29.x, r29.y
              else 
                mov r29.xy, l(-1,-1,0,0)
              endif 
              and r29.xy, r20.wwww, r29.yxyy
              or r34.xy, r19.xxxx, r29.yxyy
            else 
              mov r34.xy, l(-1,-1,0,0)
            endif 
            not r19.x, r34.y
            not r20.w, r34.x
            and r19.x, r19.x, r20.w
            if_nz r19.x
              mul r29.xyz, r21.xyzx, r31.yzxy
              mad r29.xyz, r31.xyzx, r21.yzxy, -r29.xyzx
              dp3 r19.x, r27.xyzx, r29.xyzx
              dp3 r20.w, r28.xyzx, r29.xyzx
              dp3 r21.w, r32.xyzx, r29.xyzx
              add r20.w, |r20.w|, |r21.w|
              dp3 r21.w, r33.xyzx, r29.xyzx
              add r20.w, r20.w, |r21.w|
              add r21.w, r19.x, -r20.w
              add r19.x, r19.x, r20.w
              dp3 r20.w, r11.xyzx, r29.xyzx
              dp3 r23.w, r13.xyzx, r29.xyzx
              dp3 r24.w, r14.xyzx, r29.xyzx
              add r23.w, |r23.w|, |r24.w|
              dp3 r24.w, r12.xyzx, r29.xyzx
              dp3 r25.w, r15.xyzx, r29.xyzx
              dp3 r26.w, r16.xyzx, r29.xyzx
              add r25.w, |r25.w|, |r26.w|
              add r26.w, r20.w, -r23.w
              add r27.x, r24.w, -r25.w
              min r26.w, r26.w, r27.x
              add r20.w, r20.w, r23.w
              add r23.w, r24.w, r25.w
              max r20.w, r20.w, r23.w
              lt r19.x, r19.x, r26.w
              lt r20.w, r20.w, r21.w
              or r34.x, r19.x, r20.w
              or r19.w, r19.w, r34.x
            endif 
          endif 
          and r19.z, r19.w, r34.x
        endif 
      endif 
      movc r27.x, r22.z, r22.x, r15.w
      ieq r19.x, r22.z, l(1)
      movc r27.y, r19.x, r15.w, r22.y
      iadd r27.z, r22.z, l(1)
      bfi r27.w, l(1), r15.w, l(1), r22.w
      movc r22.xyzw, r19.zzzz, r22.xyzw, r27.xyzw
    endif 
    ieq r15.w, r17.w, l(31)
    if_nz r15.w
      store_structured u7.x, r10.w, l(0), r22.w
      iadd r10.w, r10.w, l(1)
      mov r22.w, l(0)
    endif 
    iadd r13.w, r13.w, l(1)
  endloop 
  iadd r0.w, r0.z, l(32)
  ult r0.w, r10.w, r0.w
  if_nz r0.w
    store_structured u7.x, r10.w, l(0), r22.w
  endif 
  uge r0.w, l(2), r22.z
  ishl r3.w, r22.z, l(2)
  iadd r3.w, r3.w, l(4)
  iadd r3.w, r0.y, r3.w
  movc r0.y, r0.w, r3.w, r0.y
else 
  movc r0.y, r1.x, l(52), l(20)
  mov r22.xy, l(0,0,0,0)
endif 
if_nz cb2[0].x
  add r11.xyz, -r2.wyzw, r4.yzxy
  add r12.xyz, -r2.wyzw, r6.zxyz
  mul r13.xyz, r11.xyzx, r12.zxyz
  mad r11.xyz, r11.zxyz, r12.xyzx, -r13.xyzx
  dp3 r0.w, r11.xyzx, r11.xyzx
  rsq r0.w, r0.w
  mul r11.xyz, r0.wwww, r11.xyzx
  dp3 r0.w, r11.xyzx, r2.yzwy
  add r13.xyz, -r6.zxyz, r5.xyzx
  add r14.xyz, -r6.yzxy, r9.xyzx
  mul r15.xyz, r13.xyzx, r14.xyzx
  mad r13.xyz, r13.zxyz, r14.yzxy, -r15.xyzx
  dp3 r1.x, r13.xyzx, r13.xyzx
  rsq r1.x, r1.x
  mul r13.xyz, r1.xxxx, r13.xyzx
  dp3 r1.x, r13.xyzx, r6.xyzx
  add r6.xyz, -r9.yzxy, r7.zxyz
  add r14.xyz, -r9.xyzx, r1.zwyz
  mul r15.xyz, r6.xyzx, r14.xyzx
  mad r6.xyz, r6.zxyz, r14.yzxy, -r15.xyzx
  dp3 r3.w, r6.xyzx, r6.xyzx
  rsq r3.w, r3.w
  mul r6.xyz, r3.wwww, r6.xyzx
  dp3 r3.w, r6.yzxy, r9.xyzx
  add r3.xyz, -r1.wyzw, r3.xyzx
  add r14.xyz, -r1.zwyz, r2.zwyz
  mul r15.xyz, r3.xyzx, r14.xyzx
  mad r3.xyz, r3.zxyz, r14.yzxy, -r15.xyzx
  dp3 r4.w, r3.xyzx, r3.xyzx
  rsq r4.w, r4.w
  mul r3.xyz, r3.xyzx, r4.wwww
  dp3 r1.y, r3.xyzx, r1.yzwy
  add r9.xyz, -r2.zwyz, r9.xyzx
  mul r14.xyz, r9.xyzx, r12.xyzx
  mad r9.xyz, r12.zxyz, r9.yzxy, -r14.xyzx
  dp3 r1.z, r9.xyzx, r9.xyzx
  rsq r1.z, r1.z
  mul r9.xyz, r1.zzzz, r9.xyzx
  dp3 r1.z, r9.xyzx, r2.yzwy
  add r2.yzw, r5.xxyz, -r7.zzxy
  add r4.xyz, r4.xyzx, -r7.yzxy
  mul r5.xyz, r2.yzwy, r4.xyzx
  mad r2.yzw, r2.wwyz, r4.yyzx, -r5.xxyz
  dp3 r1.w, r2.yzwy, r2.yzwy
  rsq r1.w, r1.w
  mul r2.yzw, r1.wwww, r2.yyzw
  dp3 r1.w, r2.yzwy, r7.xyzx
  dp3 r4.x, r10.xyzx, r10.xyzx
  sqrt r4.x, r4.x
  add r4.yzw, r8.xxyz, -r10.xxyz
  add r5.xyz, r8.xyzx, r10.xyzx
  mov r5.w, r0.z
  mov r7.xyzw, l(0,0,0,0)
  mov r6.w, l(0)
  loop 
    uge r8.w, r6.w, cb2[0].x
    breakc_nz r8.w
    and r8.w, r6.w, l(31)
    ld_structured_indexable(structured_buffer, stride=80)(mixed,mixed,mixed,mixed) r12.xyzw, r6.w, l(0), t11.xyzw
    ld_structured_indexable(structured_buffer, stride=80)(mixed,mixed,mixed,mixed) r14.xyzw, r6.w, l(16), t11.zwxy
    add r15.xyz, -r8.xyzx, r12.xyzx
    mov r16.x, r12.w
    mov r16.yz, r14.zzwz
    add r17.xyz, r10.xyzx, r16.xyzx
    lt r15.xyz, r17.xyzx, |r15.xyzx|
    or r9.w, r15.y, r15.x
    or r9.w, r15.z, r9.w
    if_z r9.w
      ld_structured_indexable(structured_buffer, stride=80)(mixed,mixed,mixed,mixed) r15.xyzw, r6.w, l(32), t11.xyzw
      ld_structured_indexable(structured_buffer, stride=80)(mixed,mixed,mixed,mixed) r17.xy, r6.w, l(48), t11.xyxx
      lt r9.w, l(0.000000), r17.x
      mov r14.z, r15.x
      add r14.xyz, r8.xyzx, -r14.xyzx
      dp3 r10.w, r14.xyzx, r15.yzwy
      ge r11.w, r10.w, r4.x
      mad r14.xyz, -r15.yzwy, r10.wwww, r14.xyzx
      dp3 r12.w, r14.xyzx, r14.xyzx
      mul r13.w, r17.x, r17.x
      mad r10.w, r17.y, r10.w, -r4.x
      mul r12.w, r12.w, r13.w
      mul r10.w, r10.w, r10.w
      ge r10.w, r12.w, r10.w
      or r10.w, r11.w, r10.w
      max r14.xyz, r4.yzwy, r15.yzwy
      min r14.xyz, r5.xyzx, r14.xyzx
      add r14.xyz, -r14.xyzx, r15.yzwy
      dp3 r11.w, r14.xyzx, r14.xyzx
      lt r11.w, r13.w, r11.w
      or r11.w, r9.w, r11.w
      movc r9.w, r9.w, r10.w, l(-1)
      and r9.w, r11.w, r9.w
    else 
      mov r9.w, l(-1)
    endif 
    if_z r9.w
      dp3 r9.w, r12.xyzx, r11.xyzx
      dp3 r10.w, r16.xyzx, |r11.xyzx|
      add r9.w, r9.w, r10.w
      lt r9.w, r9.w, r0.w
      not r10.w, r9.w
      dp3 r11.w, r12.xyzx, r13.xyzx
      dp3 r12.w, r16.xyzx, |r13.xyzx|
      add r11.w, r11.w, r12.w
      lt r11.w, r11.w, r1.x
      or r11.w, r9.w, r11.w
      and r10.w, r10.w, r11.w
      or r9.w, r9.w, r10.w
      dp3 r10.w, r12.xyzx, r6.xyzx
      dp3 r11.w, r16.xyzx, |r6.xyzx|
      add r10.w, r10.w, r11.w
      lt r10.w, r10.w, r3.w
      or r9.w, r9.w, r10.w
      dp3 r10.w, r12.xyzx, r3.xyzx
      dp3 r11.w, r16.xyzx, |r3.xyzx|
      add r10.w, r10.w, r11.w
      lt r10.w, r10.w, r1.y
      or r9.w, r9.w, r10.w
      dp3 r10.w, r12.xyzx, r9.xyzx
      dp3 r11.w, r16.xyzx, |r9.xyzx|
      add r10.w, r10.w, r11.w
      lt r10.w, r10.w, r1.z
      or r9.w, r9.w, r10.w
      dp3 r10.w, r12.xyzx, r2.yzwy
      dp3 r11.w, r16.xyzx, |r2.yzwy|
      add r10.w, r10.w, r11.w
      lt r10.w, r10.w, r1.w
      or r9.w, r9.w, r10.w
      movc r12.x, r7.z, r7.x, r6.w
      ieq r10.w, r7.z, l(1)
      movc r12.y, r10.w, r6.w, r7.y
      iadd r12.z, r7.z, l(1)
      bfi r12.w, l(1), r6.w, l(1), r7.w
      movc r7.xyzw, r9.wwww, r7.xyzw, r12.xyzw
    endif 
    ieq r8.w, r8.w, l(31)
    if_nz r8.w
      store_structured u7.x, r5.w, l(0), r7.w
      iadd r5.w, r5.w, l(1)
      mov r7.w, l(0)
    endif 
    iadd r6.w, r6.w, l(1)
  endloop 
  iadd r0.z, r0.z, l(16)
  ult r0.z, r5.w, r0.z
  if_nz r0.z
    store_structured u7.x, r5.w, l(0), r7.w
  endif 
  uge r0.z, l(2), r7.z
  iadd r0.w, r7.z, l(1)
  iadd r0.w, r0.y, r0.w
  movc r1.x, r0.z, r0.w, r0.y
else 
  or r1.x, r0.y, l(17)
  mov r7.xy, l(0,0,0,0)
endif 
mov r1.y, l(0)
imm_atomic_iadd r3.x, u6, r1.xyxx, l(1)
imad r0.y, r1.x, cb2[57].x, r3.x
bfi r0.z, l(10), l(12), r7.y, l(0)
bfi r0.z, l(8), l(24), r7.x, r0.z
bfi r1.x, l(12), l(0), r2.x, r0.z
bfi r0.z, l(10), l(12), r22.y, l(0)
bfi r0.z, l(8), l(24), r22.x, r0.z
bfi r1.y, l(12), l(0), r0.x, r0.z
store_structured u5.xy, r0.y, l(0), r1.xyxx
ret 
// Approximately 1212 instruction slots used
