//
// Generated by Microsoft (R) HLSL Shader Compiler 9.30.9200.16384
//
//   using 3Dmigoto v1.2.45 on Thu Jul 15 15:43:54 2021
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// volumeLightSamplerState           sampler      NA          NA             s1      1 
// volumeLightTexture                texture  float4          2d             t0      1 
// blendTexture                      texture  float4          2d             t5      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_sampler s1, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_resource_texture2d (float,float,float,float) t5
dcl_input_ps_siv linear noperspective v0.xy, position
dcl_output o0.xyzw
dcl_temps 4
ftoi r0.xy, v0.xyxx
mov r0.zw, l(0,0,0,0)
ld_indexable(texture2d)(float,float,float,float) r0.xyz, r0.xyzw, t5.xyzw
resinfo_indexable(texture2d)(float,float,float,float)_uint r1.xy, l(0), t0.xyzw
utof r1.xy, r1.xyxx
rcp r1.xy, r1.xyxx
mul r1.zw, v0.xxxy, l(0.000000, 0.000000, 0.500000, 0.500000)
round_ni r1.zw, r1.zzzw
add r1.zw, r1.zzzw, l(0.000000, 0.000000, 0.500000, 0.500000)
mul r1.xy, r1.xyxx, r1.zwzz
gather4_indexable(texture2d)(float,float,float,float) r2.xyzw, r1.xyxx, t0.xyzw, s1.x
dp4 r2.x, l(1.000000, 1.000000, 1.000000, 1.000000), r2.xyzw
gather4_indexable(texture2d)(float,float,float,float) r3.xyzw, r1.xyxx, t0.xyzw, s1.y
gather4_indexable(texture2d)(float,float,float,float) r1.xyzw, r1.xyxx, t0.xyzw, s1.z
dp4 r2.z, l(1.000000, 1.000000, 1.000000, 1.000000), r1.xyzw
dp4 r2.y, l(1.000000, 1.000000, 1.000000, 1.000000), r3.xyzw
mad o0.xyz, r2.xyzx, l(0.250000, 0.250000, 0.250000, 0.000000), r0.xyzx
mov o0.w, l(0)
ret 
// Approximately 19 instruction slots used
